-- =============================================================================
-- PASTELERIA ERP - V2 ERP TRANSICIONAL EN 3FN (SCAFFOLDING CONTROLADO)
-- Tanda: T07 - Base de datos V1/V2 y migraciones por ambiente
--
-- Esta migración NO borra tablas V1 ni intenta terminar todo el ERP en una sola
-- pasada. Crea los schemas objetivo y las tablas mínimas de control para poder
-- migrar por fases sin romper backend/admin/storefront.
--
-- La V2 completa se irá expandiendo en las tandas T09..T21 antes de producción
-- real. Mientras no exista despliegue productivo, esta V2 puede seguirse
-- refinando como baseline ERP.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS seguridad;
CREATE SCHEMA IF NOT EXISTS terceros;
CREATE SCHEMA IF NOT EXISTS inventario;
CREATE SCHEMA IF NOT EXISTS comercial;
CREATE SCHEMA IF NOT EXISTS compras;
CREATE SCHEMA IF NOT EXISTS produccion;
CREATE SCHEMA IF NOT EXISTS cartera;
CREATE SCHEMA IF NOT EXISTS tesoreria;
CREATE SCHEMA IF NOT EXISTS fiscal;
CREATE SCHEMA IF NOT EXISTS contabilidad;
CREATE SCHEMA IF NOT EXISTS inteligencia;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS auditoria;
CREATE SCHEMA IF NOT EXISTS ayuda;

COMMENT ON SCHEMA core IS 'Configuración transversal, empresa/sucursal, secuencias y mapeos legacy.';
COMMENT ON SCHEMA seguridad IS 'Usuarios, roles, permisos y asignaciones por sucursal.';
COMMENT ON SCHEMA terceros IS 'Terceros unificados: clientes, proveedores y empleados como perfiles.';
COMMENT ON SCHEMA inventario IS 'Item maestro, almacenes, stock, movimientos y costos.';
COMMENT ON SCHEMA comercial IS 'Cotizaciones, pedidos, documentos de venta y catálogo vendible.';
COMMENT ON SCHEMA compras IS 'Órdenes, recepciones, documentos de compra y proveedores por item.';
COMMENT ON SCHEMA produccion IS 'Recetas técnicas, órdenes de producción, consumos, mermas y lotes.';
COMMENT ON SCHEMA cartera IS 'Cuentas por cobrar, cobranzas, cuentas por pagar y pagos.';
COMMENT ON SCHEMA tesoreria IS 'Caja operativa, bancos, movimientos, depósitos y conciliación.';
COMMENT ON SCHEMA fiscal IS 'Documentos fiscales preparados, impuestos, retenciones y RIDE preliminar.';
COMMENT ON SCHEMA contabilidad IS 'Plan de cuentas, diarios, asientos, mayor, saldos y cierres.';
COMMENT ON SCHEMA inteligencia IS 'Vistas semánticas y datasets de consulta/reportes.';
COMMENT ON SCHEMA staging IS 'Importaciones, cargas y migración controlada.';
COMMENT ON SCHEMA auditoria IS 'Eventos auditables y trazabilidad operativa.';
COMMENT ON SCHEMA ayuda IS 'Guía operativa, casos de uso y manuales de usuario final.';

CREATE TABLE IF NOT EXISTS core.erp_migration_marker (
    marker_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    descripcion TEXT NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE core.erp_migration_marker IS 'Marcadores de adopción ERP para documentar hitos de migración V1 -> V2.';

CREATE TABLE IF NOT EXISTS core.legacy_objeto_mapeo (
    legacy_mapeo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origen_tabla VARCHAR(80) NOT NULL,
    origen_id VARCHAR(80) NOT NULL,
    destino_schema VARCHAR(80) NOT NULL,
    destino_tabla VARCHAR(80) NOT NULL,
    destino_id VARCHAR(80) NOT NULL,
    contexto VARCHAR(120),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_legacy_objeto_mapeo_origen UNIQUE (origen_tabla, origen_id, destino_schema, destino_tabla)
);

COMMENT ON TABLE core.legacy_objeto_mapeo IS 'Puente de trazabilidad para migrar IDs V1 BIGINT hacia entidades ERP V2 por fases.';
COMMENT ON COLUMN core.legacy_objeto_mapeo.origen_tabla IS 'Tabla V1/public de origen, por ejemplo cliente, producto, proveedor, pedido.';
COMMENT ON COLUMN core.legacy_objeto_mapeo.destino_schema IS 'Schema ERP destino, por ejemplo terceros, inventario, comercial.';

INSERT INTO core.erp_migration_marker (codigo, descripcion)
VALUES ('T07_V2_SCAFFOLDING', 'Schemas ERP y tablas de control creadas para migración transicional V1 -> V2.')
ON CONFLICT (codigo) DO NOTHING;

-- =============================================================================
-- T09 - Seguridad ERP transicional: empresa, sucursal, roles y permisos.
-- Estas tablas preparan la V2 normalizada sin romper el login V1 basado en
-- usuario_sistema/rol_usuario. El backend usa una proyeccion transicional hasta
-- que la migracion completa de usuarios se ejecute en tandas posteriores.
-- =============================================================================

CREATE TABLE IF NOT EXISTS core.organizacion_empresa (
    empresa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre_comercial VARCHAR(160) NOT NULL,
    razon_social VARCHAR(160),
    moneda_base VARCHAR(3) NOT NULL DEFAULT 'USD',
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS core.sucursal_operativa (
    sucursal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES core.organizacion_empresa(empresa_id),
    codigo VARCHAR(40) NOT NULL,
    nombre VARCHAR(160) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_sucursal_operativa_codigo UNIQUE (empresa_id, codigo)
);

CREATE TABLE IF NOT EXISTS seguridad.permiso_operacion (
    permiso_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    modulo VARCHAR(80) NOT NULL,
    descripcion TEXT NOT NULL,
    alcance VARCHAR(20) NOT NULL CHECK (alcance IN ('GLOBAL','SUCURSAL')),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS seguridad.rol_operacion (
    rol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    descripcion TEXT,
    alcance VARCHAR(20) NOT NULL CHECK (alcance IN ('GLOBAL','SUCURSAL')),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS seguridad.rol_permiso (
    rol_id BIGINT NOT NULL REFERENCES seguridad.rol_operacion(rol_id) ON DELETE CASCADE,
    permiso_id BIGINT NOT NULL REFERENCES seguridad.permiso_operacion(permiso_id) ON DELETE CASCADE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (rol_id, permiso_id)
);

CREATE TABLE IF NOT EXISTS seguridad.usuario_rol_global_mapeo (
    usuario_id BIGINT NOT NULL,
    rol_id BIGINT NOT NULL REFERENCES seguridad.rol_operacion(rol_id),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (usuario_id, rol_id)
);

CREATE TABLE IF NOT EXISTS seguridad.usuario_sucursal_mapeo (
    usuario_id BIGINT NOT NULL,
    sucursal_id BIGINT NOT NULL REFERENCES core.sucursal_operativa(sucursal_id),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (usuario_id, sucursal_id)
);

CREATE TABLE IF NOT EXISTS seguridad.usuario_sucursal_rol_mapeo (
    usuario_id BIGINT NOT NULL,
    sucursal_id BIGINT NOT NULL REFERENCES core.sucursal_operativa(sucursal_id),
    rol_id BIGINT NOT NULL REFERENCES seguridad.rol_operacion(rol_id),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (usuario_id, sucursal_id, rol_id)
);

COMMENT ON TABLE core.organizacion_empresa IS 'Empresa base del ERP de pasteleria. Preparada para migrar desde configuracion V1.';
COMMENT ON TABLE core.sucursal_operativa IS 'Sucursal operativa usada por caja, inventario, produccion y permisos locales.';
COMMENT ON TABLE seguridad.permiso_operacion IS 'Catalogo persistente de permisos tecnicos centralizados.';
COMMENT ON TABLE seguridad.rol_operacion IS 'Roles ERP globales o por sucursal.';
COMMENT ON TABLE seguridad.rol_permiso IS 'Matriz rol-permiso para autorizacion backend.';
COMMENT ON TABLE seguridad.usuario_rol_global_mapeo IS 'Mapeo transicional de usuarios V1 a roles globales ERP.';
COMMENT ON TABLE seguridad.usuario_sucursal_mapeo IS 'Mapeo transicional de usuarios V1 a sucursales operables.';
COMMENT ON TABLE seguridad.usuario_sucursal_rol_mapeo IS 'Mapeo transicional de roles por sucursal para usuarios V1.';

INSERT INTO core.organizacion_empresa (codigo, nombre_comercial, razon_social, moneda_base)
VALUES ('PASTELERIA_BASE', 'Pastelería Artesanal', 'Pastelería Artesanal', 'USD')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO core.sucursal_operativa (empresa_id, codigo, nombre, principal)
SELECT empresa_id, 'MATRIZ', 'Sucursal principal', TRUE
FROM core.organizacion_empresa
WHERE codigo = 'PASTELERIA_BASE'
ON CONFLICT (empresa_id, codigo) DO NOTHING;

INSERT INTO seguridad.rol_operacion (codigo, nombre, descripcion, alcance) VALUES
  ('ADMIN_GLOBAL', 'Administrador global', 'Administra configuracion, seguridad y operación completa.', 'GLOBAL'),
  ('ATENCION', 'Atención y caja', 'Gestiona clientes, cotizaciones, pedidos y caja de sucursal.', 'SUCURSAL'),
  ('PRODUCCION', 'Producción', 'Opera producción, recetas, inventario y abastecimiento de sucursal.', 'SUCURSAL')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO seguridad.permiso_operacion (codigo, modulo, descripcion, alcance) VALUES
  ('CLIENTES_VER', 'Clientes', 'Consultar clientes.', 'SUCURSAL'),
  ('CLIENTES_GESTIONAR', 'Clientes', 'Crear y mantener clientes.', 'SUCURSAL'),
  ('PRODUCTOS_VER', 'Productos', 'Consultar productos.', 'SUCURSAL'),
  ('PRODUCTOS_GESTIONAR', 'Productos', 'Crear y mantener productos.', 'SUCURSAL'),
  ('COTIZACIONES_VER', 'Cotizaciones', 'Consultar cotizaciones.', 'SUCURSAL'),
  ('COTIZACIONES_GESTIONAR', 'Cotizaciones', 'Crear y gestionar cotizaciones.', 'SUCURSAL'),
  ('PEDIDOS_VER', 'Pedidos', 'Consultar pedidos.', 'SUCURSAL'),
  ('PEDIDOS_GESTIONAR', 'Pedidos', 'Crear y gestionar pedidos.', 'SUCURSAL'),
  ('PRODUCCION_VER', 'Producción', 'Consultar producción.', 'SUCURSAL'),
  ('PRODUCCION_OPERAR', 'Producción', 'Operar producción.', 'SUCURSAL'),
  ('RECETAS_VER', 'Recetas', 'Consultar recetas técnicas.', 'SUCURSAL'),
  ('RECETAS_GESTIONAR', 'Recetas', 'Crear y mantener recetas técnicas.', 'SUCURSAL'),
  ('INVENTARIO_VER', 'Inventario', 'Consultar inventario.', 'SUCURSAL'),
  ('INVENTARIO_OPERAR', 'Inventario', 'Registrar movimientos de inventario.', 'SUCURSAL'),
  ('TERCEROS_VER', 'Terceros', 'Consultar vista unificada de terceros.', 'SUCURSAL'),
  ('TERCEROS_GESTIONAR', 'Terceros', 'Gestionar terceros unificados en fases ERP posteriores.', 'SUCURSAL'),
  ('COMPRAS_VER', 'Compras', 'Consultar compras y proveedores.', 'SUCURSAL'),
  ('COMPRAS_GESTIONAR', 'Compras', 'Gestionar compras y recepciones.', 'SUCURSAL'),
  ('CAJA_VER', 'Caja', 'Consultar caja.', 'SUCURSAL'),
  ('CAJA_OPERAR', 'Caja', 'Operar caja.', 'SUCURSAL'),
  ('CARTERA_VER', 'Cartera', 'Consultar cuentas por cobrar.', 'SUCURSAL'),
  ('COBRANZAS_REGISTRAR', 'Cartera', 'Registrar cobranzas.', 'SUCURSAL'),
  ('CUENTAS_PAGAR_VER', 'Cuentas por pagar', 'Consultar cuentas por pagar.', 'SUCURSAL'),
  ('PAGOS_PROVEEDOR_REGISTRAR', 'Cuentas por pagar', 'Registrar pagos a proveedor.', 'SUCURSAL'),
  ('TESORERIA_VER', 'Tesorería', 'Consultar tesorería.', 'GLOBAL'),
  ('CONTABILIDAD_VER', 'Contabilidad', 'Consultar contabilidad.', 'GLOBAL'),
  ('ASIENTOS_REGISTRAR', 'Contabilidad', 'Registrar asientos.', 'GLOBAL'),
  ('FISCAL_VER', 'Fiscal', 'Consultar fiscalidad preparada.', 'GLOBAL'),
  ('DOCUMENTOS_FISCALES_EMITIR', 'Fiscal', 'Preparar documentos fiscales.', 'GLOBAL'),
  ('ARCHIVOS_DESCARGAR', 'Archivos', 'Descargar archivos internos.', 'GLOBAL'),
  ('REPORTES_VER', 'Reportes', 'Consultar reportes.', 'GLOBAL'),
  ('REPORTES_SOLICITAR', 'Reportes', 'Solicitar reportes.', 'GLOBAL'),
  ('AUDITORIA_VER', 'Auditoría', 'Consultar auditoría.', 'GLOBAL'),
  ('GUIA_OPERATIVA_VER', 'Guía Operativa', 'Consultar guía operativa.', 'GLOBAL'),
  ('SOPORTE_VER', 'Soporte', 'Consultar soporte.', 'GLOBAL'),
  ('SOPORTE_GESTIONAR', 'Soporte', 'Gestionar soporte.', 'GLOBAL'),
  ('SEGURIDAD_ADMINISTRAR', 'Seguridad', 'Administrar seguridad.', 'GLOBAL'),
  ('USUARIOS_GESTIONAR', 'Usuarios', 'Gestionar usuarios.', 'GLOBAL'),
  ('CONTRATOS_API_VER', 'Contratos API', 'Consultar contratos API.', 'GLOBAL')
ON CONFLICT (codigo) DO NOTHING;

-- ADMIN_GLOBAL recibe todos los permisos. Roles de sucursal reciben solo permisos
-- de su responsabilidad operativa principal.
INSERT INTO seguridad.rol_permiso (rol_id, permiso_id)
SELECT r.rol_id, p.permiso_id
FROM seguridad.rol_operacion r
CROSS JOIN seguridad.permiso_operacion p
WHERE r.codigo = 'ADMIN_GLOBAL'
ON CONFLICT DO NOTHING;

INSERT INTO seguridad.rol_permiso (rol_id, permiso_id)
SELECT r.rol_id, p.permiso_id
FROM seguridad.rol_operacion r
JOIN seguridad.permiso_operacion p ON p.codigo IN (
  'CLIENTES_VER','CLIENTES_GESTIONAR','TERCEROS_VER','PRODUCTOS_VER','COTIZACIONES_VER','COTIZACIONES_GESTIONAR',
  'PEDIDOS_VER','PEDIDOS_GESTIONAR','CAJA_VER','CAJA_OPERAR','REPORTES_VER','GUIA_OPERATIVA_VER','ARCHIVOS_DESCARGAR'
)
WHERE r.codigo = 'ATENCION'
ON CONFLICT DO NOTHING;

INSERT INTO seguridad.rol_permiso (rol_id, permiso_id)
SELECT r.rol_id, p.permiso_id
FROM seguridad.rol_operacion r
JOIN seguridad.permiso_operacion p ON p.codigo IN (
  'PRODUCTOS_VER','PEDIDOS_VER','PRODUCCION_VER','PRODUCCION_OPERAR','RECETAS_VER','RECETAS_GESTIONAR',
  'INVENTARIO_VER','INVENTARIO_OPERAR','TERCEROS_VER','COMPRAS_VER','REPORTES_VER','GUIA_OPERATIVA_VER','ARCHIVOS_DESCARGAR'
)
WHERE r.codigo = 'PRODUCCION'
ON CONFLICT DO NOTHING;

INSERT INTO core.erp_migration_marker (codigo, descripcion)
VALUES ('T09_SEGURIDAD_TRANSICIONAL', 'Empresa, sucursal, roles y permisos ERP preparados sin romper usuario_sistema V1.')
ON CONFLICT (codigo) DO NOTHING;


-- =============================================================================
-- T11 - Caja operativa ERP transicional
-- =============================================================================
CREATE TABLE IF NOT EXISTS tesoreria.caja_operativa (
    caja_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id BIGINT REFERENCES core.sucursal_operativa(sucursal_id),
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    tipo_caja VARCHAR(30) NOT NULL DEFAULT 'VENTA' CHECK (tipo_caja IN ('VENTA','CAJA_CHICA','EVENTO','DELIVERY','OTRA')),
    moneda VARCHAR(3) NOT NULL DEFAULT 'USD',
    saldo_actual NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (saldo_actual >= 0),
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tesoreria.turno_caja (
    turno_caja_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_id BIGINT NOT NULL REFERENCES tesoreria.caja_operativa(caja_id),
    usuario_apertura_id BIGINT NOT NULL,
    usuario_cierre_id BIGINT,
    fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_cierre TIMESTAMPTZ,
    monto_apertura NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (monto_apertura >= 0),
    monto_cierre_sistema NUMERIC(12,2),
    monto_cierre_declarado NUMERIC(12,2),
    diferencia_cierre NUMERIC(12,2),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ABIERTO','CERRADO','ANULADO')),
    observaciones_apertura VARCHAR(500),
    observaciones_cierre VARCHAR(500),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tesoreria_turno_caja_unico_abierto
    ON tesoreria.turno_caja (caja_id)
    WHERE estado = 'ABIERTO';

CREATE TABLE IF NOT EXISTS tesoreria.movimiento_caja (
    movimiento_caja_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_caja_id BIGINT NOT NULL REFERENCES tesoreria.turno_caja(turno_caja_id),
    tipo_movimiento VARCHAR(40) NOT NULL,
    naturaleza VARCHAR(20) NOT NULL CHECK (naturaleza IN ('ENTRADA','SALIDA','AJUSTE')),
    fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    monto NUMERIC(12,2) NOT NULL CHECK (monto > 0),
    moneda VARCHAR(3) NOT NULL DEFAULT 'USD',
    referencia_tipo VARCHAR(80),
    referencia_id VARCHAR(120),
    descripcion VARCHAR(500),
    estado VARCHAR(20) NOT NULL DEFAULT 'REGISTRADO' CHECK (estado IN ('REGISTRADO','ANULADO')),
    creado_por_usuario_id BIGINT NOT NULL,
    anulado_por_usuario_id BIGINT,
    anulado_en TIMESTAMPTZ,
    motivo_anulacion VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS tesoreria.arqueo_caja (
    arqueo_caja_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_caja_id BIGINT NOT NULL REFERENCES tesoreria.turno_caja(turno_caja_id),
    fecha_arqueo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    monto_sistema NUMERIC(12,2) NOT NULL CHECK (monto_sistema >= 0),
    monto_declarado NUMERIC(12,2) NOT NULL CHECK (monto_declarado >= 0),
    diferencia NUMERIC(12,2) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'CONFIRMADO' CHECK (estado IN ('BORRADOR','CONFIRMADO','APROBADO','ANULADO')),
    observaciones VARCHAR(500),
    creado_por_usuario_id BIGINT NOT NULL
);

INSERT INTO tesoreria.caja_operativa (sucursal_id, codigo, nombre, tipo_caja, moneda, saldo_actual, activa)
SELECT s.sucursal_id, 'CAJA_MATRIZ', 'Caja principal', 'VENTA', 'USD', 0.00, TRUE
FROM core.sucursal_operativa s
WHERE s.codigo = 'MATRIZ'
ON CONFLICT (codigo) DO NOTHING;

COMMENT ON TABLE tesoreria.caja_operativa IS 'Caja operativa formal del ERP. En V1 existe espejo public.caja_operativa para compatibilidad JPA.';
COMMENT ON TABLE tesoreria.turno_caja IS 'Turnos de caja con apertura, cierre y arqueo.';
COMMENT ON TABLE tesoreria.movimiento_caja IS 'Movimientos de caja por turno, con naturaleza entrada/salida/ajuste.';
COMMENT ON TABLE tesoreria.arqueo_caja IS 'Arqueos de cierre o revisión de caja.';

INSERT INTO core.erp_migration_marker (codigo, descripcion)
VALUES ('T11_CAJA_OPERATIVA_TRANSICIONAL', 'Caja operativa, turnos, movimientos y arqueo preparados para ERP sin romper V1.')
ON CONFLICT (codigo) DO NOTHING;

-- =============================================================================
-- T13 - Producción técnica transicional: consumos, lotes y entradas documentales
-- =============================================================================
CREATE TABLE IF NOT EXISTS produccion.consumo_material (
    consumo_material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produccion_legacy_id BIGINT NOT NULL,
    pedido_detalle_legacy_id BIGINT NOT NULL,
    receta_legacy_id BIGINT,
    detalle_receta_legacy_id BIGINT,
    ingrediente_legacy_id BIGINT NOT NULL,
    cantidad_teorica NUMERIC(12,4) NOT NULL CHECK (cantidad_teorica > 0),
    cantidad_consumida NUMERIC(12,4) NOT NULL CHECK (cantidad_consumida > 0),
    costo_unitario NUMERIC(12,4),
    costo_total NUMERIC(12,4),
    movimiento_inventario_legacy_id BIGINT,
    observaciones VARCHAR(500),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS produccion.lote_produccion (
    lote_produccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produccion_legacy_id BIGINT NOT NULL,
    pedido_detalle_legacy_id BIGINT NOT NULL,
    producto_legacy_id BIGINT NOT NULL,
    codigo_lote VARCHAR(80) NOT NULL UNIQUE,
    fecha_produccion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cantidad_producida NUMERIC(12,4) NOT NULL CHECK (cantidad_producida > 0),
    cantidad_disponible NUMERIC(12,4) NOT NULL CHECK (cantidad_disponible >= 0),
    costo_total_estimado NUMERIC(12,4),
    estado VARCHAR(30) NOT NULL DEFAULT 'DISPONIBLE' CHECK (estado IN ('DISPONIBLE','CONSUMIDO','VENDIDO','VENCIDO','ANULADO')),
    observaciones VARCHAR(500),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS produccion.entrada_producto_terminado (
    entrada_producto_terminado_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_produccion_id BIGINT NOT NULL REFERENCES produccion.lote_produccion(lote_produccion_id),
    produccion_legacy_id BIGINT NOT NULL,
    producto_legacy_id BIGINT NOT NULL,
    cantidad NUMERIC(12,4) NOT NULL CHECK (cantidad > 0),
    costo_total_estimado NUMERIC(12,4),
    observaciones VARCHAR(500),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS produccion.merma_produccion (
    merma_produccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produccion_legacy_id BIGINT,
    producto_legacy_id BIGINT,
    ingrediente_legacy_id BIGINT,
    tipo_merma VARCHAR(40) NOT NULL DEFAULT 'OTRO',
    cantidad NUMERIC(12,4) NOT NULL CHECK (cantidad > 0),
    costo_estimado NUMERIC(12,4),
    motivo VARCHAR(500) NOT NULL,
    movimiento_inventario_legacy_id BIGINT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE produccion.consumo_material IS 'Consumos técnicos de producción. En T13 se espeja conceptualmente desde public.consumo_material_produccion.';
COMMENT ON TABLE produccion.lote_produccion IS 'Lotes documentales de producto terminado por producción.';
COMMENT ON TABLE produccion.entrada_producto_terminado IS 'Entradas documentales de producto terminado generadas desde lotes.';
COMMENT ON TABLE produccion.merma_produccion IS 'Mermas preparadas para fases posteriores de producción e inventario.';

INSERT INTO core.erp_migration_marker (codigo, descripcion)
VALUES ('T13_PRODUCCION_TECNICA_TRANSICIONAL', 'Consumos, lotes, entradas de producto terminado y merma preparada para ERP sin romper V1.')
ON CONFLICT (codigo) DO NOTHING;

-- =============================================================================
-- T14 - Compras financieras transicionales.
-- Prepara orden -> recepcion -> documento de compra -> cuenta por pagar sin
-- activar todavia pagos ni contabilidad completa.
-- =============================================================================

CREATE TABLE IF NOT EXISTS compras.documento_compra (
    documento_compra_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_documento_compra_id BIGINT,
    legacy_orden_compra_id BIGINT,
    legacy_proveedor_id BIGINT,
    numero_documento VARCHAR(60) NOT NULL,
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('BORRADOR','REGISTRADO','ANULADO')),
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
    impuesto NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (impuesto >= 0),
    total NUMERIC(12,2) NOT NULL CHECK (total > 0),
    observaciones TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_compras_documento_compra_legacy_orden UNIQUE (legacy_orden_compra_id),
    CONSTRAINT uq_compras_documento_compra_numero UNIQUE (numero_documento)
);

CREATE TABLE IF NOT EXISTS cartera.documento_pagar (
    documento_pagar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_documento_pagar_id BIGINT,
    documento_compra_id BIGINT REFERENCES compras.documento_compra(documento_compra_id),
    legacy_proveedor_id BIGINT,
    codigo VARCHAR(60) NOT NULL UNIQUE,
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('PENDIENTE','PAGADO_PARCIAL','PAGADO','ANULADO')),
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_vencimiento TIMESTAMPTZ,
    total NUMERIC(12,2) NOT NULL CHECK (total > 0),
    saldo NUMERIC(12,2) NOT NULL CHECK (saldo >= 0),
    observaciones TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_cartera_documento_pagar_saldo_total CHECK (saldo <= total)
);

COMMENT ON TABLE compras.documento_compra IS 'Documento de compra transicional generado desde ordenes recibidas.';
COMMENT ON TABLE cartera.documento_pagar IS 'Cuenta por pagar transicional asociada a documentos de compra.';


-- =============================================================================
-- T17 - Cartera, cobranzas y pagos a proveedores.
-- Añade documentos por cobrar, cobranzas aplicadas y pagos a proveedor sin
-- activar todavia contabilidad ni bridges automaticos completos.
-- =============================================================================

CREATE TABLE IF NOT EXISTS cartera.documento_cobrar (
    documento_cobrar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_documento_cobrar_id BIGINT,
    legacy_cliente_id BIGINT,
    legacy_pedido_id BIGINT,
    codigo VARCHAR(60) NOT NULL UNIQUE,
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('PENDIENTE','PARCIAL','PAGADO','ANULADO')),
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_vencimiento TIMESTAMPTZ,
    total NUMERIC(12,2) NOT NULL CHECK (total > 0),
    saldo NUMERIC(12,2) NOT NULL CHECK (saldo >= 0),
    observaciones TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_cartera_documento_cobrar_saldo_total CHECK (saldo <= total)
);

CREATE TABLE IF NOT EXISTS cartera.cobranza (
    cobranza_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_cobranza_id BIGINT,
    legacy_cliente_id BIGINT,
    codigo VARCHAR(60) NOT NULL UNIQUE,
    fecha_cobranza TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    monto_total NUMERIC(12,2) NOT NULL CHECK (monto_total > 0),
    medio_pago VARCHAR(40),
    referencia_pago VARCHAR(120),
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('REGISTRADA','ANULADA')),
    observaciones TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cartera.cobranza_detalle (
    cobranza_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cobranza_id BIGINT NOT NULL REFERENCES cartera.cobranza(cobranza_id) ON DELETE CASCADE,
    documento_cobrar_id BIGINT NOT NULL REFERENCES cartera.documento_cobrar(documento_cobrar_id),
    monto_aplicado NUMERIC(12,2) NOT NULL CHECK (monto_aplicado > 0),
    saldo_anterior NUMERIC(12,2) NOT NULL CHECK (saldo_anterior >= 0),
    saldo_posterior NUMERIC(12,2) NOT NULL CHECK (saldo_posterior >= 0),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_cartera_cobranza_detalle_saldo CHECK (saldo_posterior <= saldo_anterior)
);

CREATE TABLE IF NOT EXISTS cartera.pago_proveedor (
    pago_proveedor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_pago_proveedor_id BIGINT,
    legacy_proveedor_id BIGINT,
    codigo VARCHAR(60) NOT NULL UNIQUE,
    fecha_pago TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    monto_total NUMERIC(12,2) NOT NULL CHECK (monto_total > 0),
    medio_pago VARCHAR(40),
    referencia_pago VARCHAR(120),
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('REGISTRADO','ANULADO')),
    observaciones TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cartera.pago_proveedor_aplicacion (
    pago_proveedor_aplicacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_proveedor_id BIGINT NOT NULL REFERENCES cartera.pago_proveedor(pago_proveedor_id) ON DELETE CASCADE,
    documento_pagar_id BIGINT NOT NULL REFERENCES cartera.documento_pagar(documento_pagar_id),
    monto_aplicado NUMERIC(12,2) NOT NULL CHECK (monto_aplicado > 0),
    saldo_anterior NUMERIC(12,2) NOT NULL CHECK (saldo_anterior >= 0),
    saldo_posterior NUMERIC(12,2) NOT NULL CHECK (saldo_posterior >= 0),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_cartera_pago_proveedor_aplicacion_saldo CHECK (saldo_posterior <= saldo_anterior)
);

CREATE INDEX IF NOT EXISTS idx_cartera_documento_cobrar_estado ON cartera.documento_cobrar(estado, fecha_vencimiento);
CREATE INDEX IF NOT EXISTS idx_cartera_cobranza_fecha ON cartera.cobranza(fecha_cobranza DESC);
CREATE INDEX IF NOT EXISTS idx_cartera_cobranza_detalle_documento ON cartera.cobranza_detalle(documento_cobrar_id);
CREATE INDEX IF NOT EXISTS idx_cartera_pago_proveedor_fecha ON cartera.pago_proveedor(fecha_pago DESC);
CREATE INDEX IF NOT EXISTS idx_cartera_pago_proveedor_aplicacion_documento ON cartera.pago_proveedor_aplicacion(documento_pagar_id);

COMMENT ON TABLE cartera.documento_cobrar IS 'Cuenta por cobrar transicional asociada a pedidos o clientes.';
COMMENT ON TABLE cartera.cobranza IS 'Cobranza registrada contra documentos por cobrar.';
COMMENT ON TABLE cartera.cobranza_detalle IS 'Aplicaciones de una cobranza contra saldos de documentos por cobrar.';
COMMENT ON TABLE cartera.pago_proveedor IS 'Pago a proveedor registrado contra documentos por pagar.';
COMMENT ON TABLE cartera.pago_proveedor_aplicacion IS 'Aplicaciones de pago proveedor contra saldos de documentos por pagar.';

INSERT INTO core.erp_migration_marker (codigo, descripcion)
VALUES ('T17_CARTERA_COBRANZAS_CXP', 'Cartera, cobranzas y pagos a proveedor preparados en V1/V2 sin contabilidad aplicada aun.')
ON CONFLICT (codigo) DO NOTHING;

-- =============================================================================
-- T15 - Terceros unificados ERP transicional
-- =============================================================================
CREATE TABLE IF NOT EXISTS terceros.tercero (
    tercero_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_tercero_id BIGINT,
    tipo_identificacion VARCHAR(30) NOT NULL DEFAULT 'NO_ESPECIFICADA',
    numero_identificacion VARCHAR(40),
    nombre_legal VARCHAR(160) NOT NULL,
    nombre_comercial VARCHAR(160),
    telefono VARCHAR(30),
    correo VARCHAR(120),
    direccion_principal VARCHAR(500),
    observaciones TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_terceros_identificacion UNIQUE (tipo_identificacion, numero_identificacion)
);

CREATE TABLE IF NOT EXISTS terceros.cliente_perfil (
    cliente_perfil_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tercero_id BIGINT NOT NULL REFERENCES terceros.tercero(tercero_id) ON DELETE CASCADE,
    legacy_cliente_id BIGINT UNIQUE,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
    fecha_alta TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_terceros_cliente_perfil_tercero UNIQUE (tercero_id)
);

CREATE TABLE IF NOT EXISTS terceros.proveedor_perfil (
    proveedor_perfil_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tercero_id BIGINT NOT NULL REFERENCES terceros.tercero(tercero_id) ON DELETE CASCADE,
    legacy_proveedor_id BIGINT UNIQUE,
    codigo_proveedor VARCHAR(40),
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
    fecha_alta TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_terceros_proveedor_perfil_tercero UNIQUE (tercero_id)
);

CREATE TABLE IF NOT EXISTS terceros.empleado_perfil (
    empleado_perfil_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tercero_id BIGINT NOT NULL REFERENCES terceros.tercero(tercero_id) ON DELETE CASCADE,
    legacy_usuario_id BIGINT UNIQUE,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
    fecha_alta TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_terceros_empleado_perfil_tercero UNIQUE (tercero_id)
);

INSERT INTO terceros.tercero (legacy_tercero_id, nombre_legal, nombre_comercial, telefono, correo, direccion_principal, observaciones, activo, creado_en, actualizado_en)
SELECT t.tercero_id, t.nombre_legal, t.nombre_comercial, t.telefono, t.correo, t.direccion_principal, t.observaciones, t.activo, t.created_at, t.updated_at
FROM public.tercero t
ON CONFLICT (tipo_identificacion, numero_identificacion) DO NOTHING;

INSERT INTO terceros.cliente_perfil (tercero_id, legacy_cliente_id, estado, fecha_alta)
SELECT tt.tercero_id, cp.cliente_id, cp.estado, cp.fecha_alta
FROM public.cliente_perfil cp
JOIN public.tercero pt ON pt.tercero_id = cp.tercero_id
JOIN terceros.tercero tt ON tt.legacy_tercero_id = pt.tercero_id
ON CONFLICT (legacy_cliente_id) DO NOTHING;

INSERT INTO terceros.proveedor_perfil (tercero_id, legacy_proveedor_id, codigo_proveedor, estado, fecha_alta)
SELECT tt.tercero_id, pp.proveedor_id, pp.codigo_proveedor, pp.estado, pp.fecha_alta
FROM public.proveedor_perfil pp
JOIN public.tercero pt ON pt.tercero_id = pp.tercero_id
JOIN terceros.tercero tt ON tt.legacy_tercero_id = pt.tercero_id
ON CONFLICT (legacy_proveedor_id) DO NOTHING;

INSERT INTO core.legacy_objeto_mapeo (origen_tabla, origen_id, destino_schema, destino_tabla, destino_id, contexto)
SELECT 'cliente', cp.legacy_cliente_id::text, 'terceros', 'tercero', cp.tercero_id::text, 'CLIENTE'
FROM terceros.cliente_perfil cp
WHERE cp.legacy_cliente_id IS NOT NULL
ON CONFLICT (origen_tabla, origen_id, destino_schema, destino_tabla)
DO UPDATE SET destino_id = excluded.destino_id, contexto = excluded.contexto;

INSERT INTO core.legacy_objeto_mapeo (origen_tabla, origen_id, destino_schema, destino_tabla, destino_id, contexto)
SELECT 'proveedor', pp.legacy_proveedor_id::text, 'terceros', 'tercero', pp.tercero_id::text, 'PROVEEDOR'
FROM terceros.proveedor_perfil pp
WHERE pp.legacy_proveedor_id IS NOT NULL
ON CONFLICT (origen_tabla, origen_id, destino_schema, destino_tabla)
DO UPDATE SET destino_id = excluded.destino_id, contexto = excluded.contexto;

COMMENT ON TABLE terceros.tercero IS 'Tercero unificado ERP transicional migrado desde clientes/proveedores V1.';
COMMENT ON TABLE terceros.cliente_perfil IS 'Perfil cliente asociado a un tercero ERP.';
COMMENT ON TABLE terceros.proveedor_perfil IS 'Perfil proveedor asociado a un tercero ERP.';
COMMENT ON TABLE terceros.empleado_perfil IS 'Perfil empleado preparado para futuras tandas de usuarios/trabajadores.';

INSERT INTO core.erp_migration_marker (codigo, descripcion)
VALUES ('T15_TERCEROS_UNIFICADOS_TRANSICIONAL', 'Terceros, perfiles y mapeos legacy preparados sin romper clientes/proveedores V1.')
ON CONFLICT (codigo) DO NOTHING;


-- =============================================================================
-- T18 - Contabilidad aplicada minima: plan de cuentas, diarios y asientos.
-- Es una capa interna trazable. No implementa cierres, mayor contable completo
-- ni fiscalidad/SRI. Los bridges automaticos llegan en T19.
-- =============================================================================

CREATE TABLE IF NOT EXISTS contabilidad.tipo_diario_contable (
    tipo_diario_contable_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contabilidad.cuenta_contable (
    cuenta_contable_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(160) NOT NULL,
    tipo_cuenta VARCHAR(30) NOT NULL CHECK (tipo_cuenta IN ('ACTIVO','PASIVO','PATRIMONIO','INGRESO','COSTO','GASTO')),
    naturaleza VARCHAR(20) NOT NULL CHECK (naturaleza IN ('DEUDORA','ACREEDORA')),
    nivel INTEGER NOT NULL CHECK (nivel >= 1),
    cuenta_padre_id BIGINT REFERENCES contabilidad.cuenta_contable(cuenta_contable_id),
    imputable BOOLEAN NOT NULL DEFAULT TRUE,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contabilidad.asiento_contable (
    asiento_contable_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_diario_contable_id BIGINT NOT NULL REFERENCES contabilidad.tipo_diario_contable(tipo_diario_contable_id),
    codigo VARCHAR(60) NOT NULL UNIQUE,
    fecha_asiento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    descripcion TEXT NOT NULL,
    origen_tipo VARCHAR(80),
    origen_id VARCHAR(80),
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('BORRADOR','REGISTRADO','ANULADO')),
    total_debe NUMERIC(12,2) NOT NULL CHECK (total_debe >= 0),
    total_haber NUMERIC(12,2) NOT NULL CHECK (total_haber >= 0),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_contabilidad_asiento_cuadre CHECK (total_debe = total_haber),
    CONSTRAINT ck_contabilidad_asiento_origen_completo CHECK (
        (origen_tipo IS NULL AND origen_id IS NULL) OR (origen_tipo IS NOT NULL AND origen_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_contabilidad_asiento_origen
    ON contabilidad.asiento_contable (origen_tipo, origen_id)
    WHERE origen_tipo IS NOT NULL AND origen_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS contabilidad.asiento_contable_detalle (
    asiento_contable_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asiento_contable_id BIGINT NOT NULL REFERENCES contabilidad.asiento_contable(asiento_contable_id) ON DELETE CASCADE,
    cuenta_contable_id BIGINT NOT NULL REFERENCES contabilidad.cuenta_contable(cuenta_contable_id),
    descripcion TEXT,
    debe NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (debe >= 0),
    haber NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (haber >= 0),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_contabilidad_detalle_debe_haber CHECK (
        (debe > 0 AND haber = 0) OR (haber > 0 AND debe = 0)
    )
);

INSERT INTO contabilidad.tipo_diario_contable (codigo, nombre, descripcion) VALUES
('VENTAS', 'Diario de ventas', 'Asientos relacionados con ventas y cartera.'),
('COMPRAS', 'Diario de compras', 'Asientos relacionados con compras y cuentas por pagar.'),
('CAJA', 'Diario de caja', 'Asientos relacionados con caja, cobros y pagos.'),
('GENERAL', 'Diario general', 'Asientos manuales y ajustes internos controlados.')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO contabilidad.cuenta_contable (codigo, nombre, tipo_cuenta, naturaleza, nivel, cuenta_padre_id, imputable, activa) VALUES
('1', 'Activo', 'ACTIVO', 'DEUDORA', 1, NULL, FALSE, TRUE),
('1.1.01', 'Caja principal', 'ACTIVO', 'DEUDORA', 3, NULL, TRUE, TRUE),
('1.2.01', 'Clientes nacionales', 'ACTIVO', 'DEUDORA', 3, NULL, TRUE, TRUE),
('2', 'Pasivo', 'PASIVO', 'ACREEDORA', 1, NULL, FALSE, TRUE),
('2.1.01', 'Proveedores nacionales', 'PASIVO', 'ACREEDORA', 3, NULL, TRUE, TRUE),
('3.1.01', 'Capital inicial', 'PATRIMONIO', 'ACREEDORA', 2, NULL, TRUE, TRUE),
('4.1.01', 'Ventas de pasteleria', 'INGRESO', 'ACREEDORA', 2, NULL, TRUE, TRUE),
('5.1.01', 'Costo de insumos de produccion', 'COSTO', 'DEUDORA', 2, NULL, TRUE, TRUE),
('6.1.01', 'Gastos operativos generales', 'GASTO', 'DEUDORA', 2, NULL, TRUE, TRUE)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO core.erp_migration_marker (codigo, descripcion)
VALUES ('T18_CONTABILIDAD_APLICADA', 'Plan de cuentas, diarios y asientos contables internos preparados en V1/V2.')
ON CONFLICT (codigo) DO NOTHING;



-- =============================================================================
-- T20 - Fiscalidad preparada y prudente.
-- Documento fiscal interno, trazable y preparado para crecer hacia SRI sin
-- declarar integracion productiva, firma, autorizacion ni RIDE final.
-- =============================================================================

CREATE TABLE IF NOT EXISTS fiscal.documento_fiscal (
    documento_fiscal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_documento_fiscal_id BIGINT,
    codigo VARCHAR(60) NOT NULL UNIQUE,
    tipo_comprobante VARCHAR(40) NOT NULL CHECK (tipo_comprobante IN ('FACTURA','NOTA_VENTA','COMPROBANTE_COMPRA_INTERNO')),
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('BORRADOR','EMITIDO_INTERNO','ANULADO')),
    documento_cobrar_id BIGINT REFERENCES cartera.documento_cobrar(documento_cobrar_id),
    documento_compra_id BIGINT REFERENCES compras.documento_compra(documento_compra_id),
    origen_tipo VARCHAR(40) NOT NULL CHECK (origen_tipo IN ('DOCUMENTO_COBRAR','DOCUMENTO_COMPRA')),
    tercero_tipo VARCHAR(30) NOT NULL CHECK (tercero_tipo IN ('CLIENTE','PROVEEDOR')),
    legacy_tercero_id BIGINT,
    tercero_nombre VARCHAR(160) NOT NULL,
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    establecimiento VARCHAR(3) NOT NULL DEFAULT '001',
    punto_emision VARCHAR(3) NOT NULL DEFAULT '001',
    secuencial VARCHAR(9) NOT NULL,
    numero_comprobante VARCHAR(20) NOT NULL UNIQUE,
    subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
    impuesto NUMERIC(12,2) NOT NULL CHECK (impuesto >= 0),
    total NUMERIC(12,2) NOT NULL CHECK (total >= 0),
    clave_acceso VARCHAR(60),
    numero_autorizacion VARCHAR(80),
    fecha_autorizacion TIMESTAMPTZ,
    ambiente VARCHAR(20) NOT NULL DEFAULT 'INTERNO',
    observaciones TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_fiscal_documento_origen_unico CHECK (
        (documento_cobrar_id IS NOT NULL AND documento_compra_id IS NULL AND origen_tipo = 'DOCUMENTO_COBRAR') OR
        (documento_cobrar_id IS NULL AND documento_compra_id IS NOT NULL AND origen_tipo = 'DOCUMENTO_COMPRA')
    ),
    CONSTRAINT ck_fiscal_documento_total CHECK (subtotal + impuesto = total)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_fiscal_documento_cobrar
    ON fiscal.documento_fiscal(documento_cobrar_id)
    WHERE documento_cobrar_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_fiscal_documento_compra
    ON fiscal.documento_fiscal(documento_compra_id)
    WHERE documento_compra_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_fiscal_documento_estado ON fiscal.documento_fiscal(estado, fecha_emision DESC);
CREATE INDEX IF NOT EXISTS idx_fiscal_documento_tercero ON fiscal.documento_fiscal(tercero_tipo, legacy_tercero_id);

COMMENT ON TABLE fiscal.documento_fiscal IS 'Documento fiscal interno preparado. No implica autorizacion SRI real ni firma electronica.';
COMMENT ON COLUMN fiscal.documento_fiscal.clave_acceso IS 'Campo reservado para futura integracion SRI; no se genera en T20.';
COMMENT ON COLUMN fiscal.documento_fiscal.numero_autorizacion IS 'Campo reservado para futura autorizacion SRI; permanece nulo en T20.';

INSERT INTO core.erp_migration_marker (codigo, descripcion)
VALUES ('T20_FISCALIDAD_PREPARADA_PRUDENTE', 'Documento fiscal interno preparado sin integracion SRI productiva.')
ON CONFLICT (codigo) DO NOTHING;

-- =============================================================================
-- T21 - Vistas semanticas e inteligencia/reportes.
-- La definicion fisica de vistas se mantiene en migraciones repeatable R__ para
-- permitir ajustes seguros sin abrir nuevas migraciones versionadas por cada vista.
-- =============================================================================

INSERT INTO core.erp_migration_marker (codigo, descripcion)
VALUES ('T21_INTELIGENCIA_REPORTING', 'Capa semantica de lectura para dashboard ERP, cartera, cuentas por pagar, caja, contabilidad y fiscalidad.')
ON CONFLICT (codigo) DO NOTHING;

-- =============================================================================
-- T25 - Auditoria, soporte y evidencia.
-- =============================================================================
INSERT INTO core.erp_migration_marker (codigo, descripcion)
VALUES ('T25_AUDITORIA_SOPORTE_EVIDENCIA', 'Consultas de auditoria, evidencia de soporte y checklist operativo agregados.')
ON CONFLICT (codigo) DO NOTHING;
