ALTER TABLE usuario_sistema
  ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE cliente
  ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE categoria_producto
  ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE producto
  ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE cotizacion
  ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE pedido
  ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE produccion
  ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
