-- =============================================================================
-- PASTELERIA - SCHEMA CANONICO
-- Version: 2026-03-25
-- Base: snapshot JPA previo + tablas faltantes del modulo compras
-- Objetivo: reflejar el modelo real que hoy consume el backend
-- =============================================================================


-- =============================================================================
-- SECCIÓN 1: LIMPIEZA
-- =============================================================================
DROP TABLE IF EXISTS cobranza_detalle CASCADE;
DROP TABLE IF EXISTS cobranza CASCADE;
DROP TABLE IF EXISTS documento_cobrar CASCADE;
DROP TABLE IF EXISTS pago_proveedor_aplicacion CASCADE;
DROP TABLE IF EXISTS pago_proveedor CASCADE;
DROP TABLE IF EXISTS arqueo_caja CASCADE;
DROP TABLE IF EXISTS movimiento_caja CASCADE;
DROP TABLE IF EXISTS turno_caja CASCADE;
DROP TABLE IF EXISTS caja_operativa CASCADE;
DROP TABLE IF EXISTS paso_caso_uso CASCADE;
DROP TABLE IF EXISTS caso_uso_operativo CASCADE;
DROP TABLE IF EXISTS caso_uso_modulo CASCADE;
DROP TABLE IF EXISTS inventario_movimiento CASCADE;
DROP TABLE IF EXISTS documento_pagar CASCADE;
DROP TABLE IF EXISTS documento_compra CASCADE;
DROP TABLE IF EXISTS orden_compra_detalle CASCADE;
DROP TABLE IF EXISTS orden_compra CASCADE;
DROP TABLE IF EXISTS item_proveedor CASCADE;
DROP TABLE IF EXISTS proveedor CASCADE;
DROP TABLE IF EXISTS insumo CASCADE;
DROP TABLE IF EXISTS ingrediente CASCADE;
DROP TABLE IF EXISTS umedida CASCADE;
DROP TABLE IF EXISTS archivo_recurso CASCADE;
DROP TABLE IF EXISTS auditoria_evento CASCADE;
DROP TABLE IF EXISTS categoria_producto CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS cotizacion_detalle CASCADE;
DROP TABLE IF EXISTS cotizacion CASCADE;
DROP TABLE IF EXISTS detalle_receta CASCADE;
DROP TABLE IF EXISTS receta CASCADE;
DROP TABLE IF EXISTS notificacion CASCADE;
DROP TABLE IF EXISTS job_reporte CASCADE;
DROP TABLE IF EXISTS pedido_detalle CASCADE;
DROP TABLE IF EXISTS pedido CASCADE;
DROP TABLE IF EXISTS produccion CASCADE;
DROP TABLE IF EXISTS producto CASCADE;
DROP TABLE IF EXISTS rol_usuario CASCADE;
DROP TABLE IF EXISTS usuario_sistema CASCADE;

-- =============================================================================
-- SECCIÓN 2: SCHEMA (Generado desde JPA Entities)
-- =============================================================================

-- Tabla: rol_usuario
CREATE TABLE rol_usuario (
    rol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    codigo VARCHAR(40) NOT NULL UNIQUE CHECK (codigo IN ('ADMIN','ATENCION','PRODUCCION')),
    nombre_rol VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

-- Tabla: usuario_sistema
CREATE TABLE usuario_sistema (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rol_id BIGINT NOT NULL REFERENCES rol_usuario(rol_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    apellidos VARCHAR(120) NOT NULL,
    correo VARCHAR(120),
    nombre_usuario VARCHAR(120) NOT NULL UNIQUE,
    nombres VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);


-- Tabla: caja_operativa
CREATE TABLE caja_operativa (
    caja_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_codigo VARCHAR(40) NOT NULL DEFAULT 'MATRIZ',
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    tipo_caja VARCHAR(30) NOT NULL DEFAULT 'VENTA' CHECK (tipo_caja IN ('VENTA','CAJA_CHICA','EVENTO','DELIVERY','OTRA')),
    moneda VARCHAR(3) NOT NULL DEFAULT 'USD',
    saldo_actual NUMERIC(12,2) NOT NULL DEFAULT 0,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_caja_operativa_saldo_no_negativo CHECK (saldo_actual >= 0)
);

-- Tabla: turno_caja
CREATE TABLE turno_caja (
    turno_caja_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_id BIGINT NOT NULL REFERENCES caja_operativa(caja_id),
    usuario_apertura_id BIGINT NOT NULL REFERENCES usuario_sistema(usuario_id),
    usuario_cierre_id BIGINT REFERENCES usuario_sistema(usuario_id),
    fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_cierre TIMESTAMPTZ,
    monto_apertura NUMERIC(12,2) NOT NULL DEFAULT 0,
    monto_cierre_sistema NUMERIC(12,2),
    monto_cierre_declarado NUMERIC(12,2),
    diferencia_cierre NUMERIC(12,2),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ABIERTO','CERRADO','ANULADO')),
    observaciones_apertura VARCHAR(500),
    observaciones_cierre VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_turno_caja_monto_apertura_no_negativo CHECK (monto_apertura >= 0)
);

CREATE UNIQUE INDEX ux_turno_caja_unico_abierto
    ON turno_caja (caja_id)
    WHERE estado = 'ABIERTO';

-- Tabla: movimiento_caja
CREATE TABLE movimiento_caja (
    movimiento_caja_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_caja_id BIGINT NOT NULL REFERENCES turno_caja(turno_caja_id),
    tipo_movimiento VARCHAR(40) NOT NULL CHECK (tipo_movimiento IN ('APERTURA','VENTA_CONTADO','COBRO_CLIENTE','INGRESO_MANUAL','PAGO_PROVEEDOR','GASTO_CAJA','RETIRO_DEPOSITO','SALIDA_MANUAL','DIFERENCIA_ARQUEO','ANULACION')),
    naturaleza VARCHAR(20) NOT NULL CHECK (naturaleza IN ('ENTRADA','SALIDA','AJUSTE')),
    fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    monto NUMERIC(12,2) NOT NULL,
    moneda VARCHAR(3) NOT NULL DEFAULT 'USD',
    referencia_tipo VARCHAR(80),
    referencia_id VARCHAR(120),
    descripcion VARCHAR(500),
    estado VARCHAR(20) NOT NULL DEFAULT 'REGISTRADO' CHECK (estado IN ('REGISTRADO','ANULADO')),
    creado_por_usuario_id BIGINT NOT NULL REFERENCES usuario_sistema(usuario_id),
    anulado_por_usuario_id BIGINT REFERENCES usuario_sistema(usuario_id),
    anulado_en TIMESTAMPTZ,
    motivo_anulacion VARCHAR(500),
    CONSTRAINT ck_movimiento_caja_monto_positivo CHECK (monto > 0)
);

CREATE INDEX idx_movimiento_caja_turno_fecha ON movimiento_caja (turno_caja_id, fecha_movimiento DESC);
CREATE INDEX idx_movimiento_caja_referencia ON movimiento_caja (referencia_tipo, referencia_id);

-- Tabla: arqueo_caja
CREATE TABLE arqueo_caja (
    arqueo_caja_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_caja_id BIGINT NOT NULL REFERENCES turno_caja(turno_caja_id),
    fecha_arqueo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    monto_sistema NUMERIC(12,2) NOT NULL,
    monto_declarado NUMERIC(12,2) NOT NULL,
    diferencia NUMERIC(12,2) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'CONFIRMADO' CHECK (estado IN ('BORRADOR','CONFIRMADO','APROBADO','ANULADO')),
    observaciones VARCHAR(500),
    creado_por_usuario_id BIGINT NOT NULL REFERENCES usuario_sistema(usuario_id),
    CONSTRAINT ck_arqueo_caja_montos_no_negativos CHECK (monto_sistema >= 0 AND monto_declarado >= 0)
);

CREATE INDEX idx_arqueo_caja_turno_fecha ON arqueo_caja (turno_caja_id, fecha_arqueo DESC);

-- Tabla: umedida
CREATE TABLE umedida (
    umedida_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    decimales SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    abreviatura VARCHAR(10) NOT NULL,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('PESO','VOLUMEN','UNIDAD','ENVASE')),
    nombre VARCHAR(60) NOT NULL
);

-- Tabla: ingrediente
CREATE TABLE ingrediente (
    ingrediente_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    costo_referencial NUMERIC(10,2),
    stock_actual NUMERIC(12,4) DEFAULT 0,
    stock_minimo NUMERIC(12,4),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    umedida_id BIGINT NOT NULL REFERENCES umedida(umedida_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500)
);

-- Tabla: insumo
CREATE TABLE insumo (
    insumo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    costo_referencial NUMERIC(10,2),
    stock_actual NUMERIC(12,4) DEFAULT 0,
    stock_minimo NUMERIC(12,4),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    umedida_id BIGINT NOT NULL REFERENCES umedida(umedida_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500)
);


-- Tabla: tercero unificado transicional
CREATE TABLE tercero (
    tercero_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_identificacion VARCHAR(30) NOT NULL DEFAULT 'NO_ESPECIFICADA',
    numero_identificacion VARCHAR(40),
    nombre_legal VARCHAR(160) NOT NULL,
    nombre_comercial VARCHAR(160),
    telefono VARCHAR(30),
    correo VARCHAR(120),
    direccion_principal VARCHAR(500),
    observaciones VARCHAR(1000),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_tercero_identificacion UNIQUE (tipo_identificacion, numero_identificacion)
);

CREATE TABLE tercero_direccion (
    tercero_direccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tercero_id BIGINT NOT NULL REFERENCES tercero(tercero_id) ON DELETE CASCADE,
    etiqueta VARCHAR(60) NOT NULL DEFAULT 'PRINCIPAL',
    direccion VARCHAR(500) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE tercero_contacto (
    tercero_contacto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tercero_id BIGINT NOT NULL REFERENCES tercero(tercero_id) ON DELETE CASCADE,
    tipo_contacto VARCHAR(30) NOT NULL CHECK (tipo_contacto IN ('TELEFONO','CORREO','WHATSAPP','OTRO')),
    valor VARCHAR(160) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE cliente_perfil (
    cliente_perfil_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tercero_id BIGINT NOT NULL REFERENCES tercero(tercero_id) ON DELETE CASCADE,
    cliente_id BIGINT NOT NULL UNIQUE,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
    fecha_alta TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_cliente_perfil_tercero UNIQUE (tercero_id)
);

CREATE TABLE proveedor_perfil (
    proveedor_perfil_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tercero_id BIGINT NOT NULL REFERENCES tercero(tercero_id) ON DELETE CASCADE,
    proveedor_id BIGINT NOT NULL UNIQUE,
    codigo_proveedor VARCHAR(40),
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
    fecha_alta TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_proveedor_perfil_tercero UNIQUE (tercero_id)
);

CREATE TABLE empleado_perfil (
    empleado_perfil_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tercero_id BIGINT NOT NULL REFERENCES tercero(tercero_id) ON DELETE CASCADE,
    usuario_id BIGINT,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
    fecha_alta TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_empleado_perfil_tercero UNIQUE (tercero_id)
);

CREATE INDEX idx_tercero_nombre ON tercero (nombre_legal);
CREATE INDEX idx_tercero_correo ON tercero (correo);

-- Tabla: proveedor
CREATE TABLE proveedor (
    proveedor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tercero_id BIGINT REFERENCES tercero(tercero_id),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    telefono VARCHAR(30),
    codigo VARCHAR(40) NOT NULL UNIQUE,
    correo VARCHAR(120),
    nombre VARCHAR(160) NOT NULL,
    direccion VARCHAR(500),
    observaciones VARCHAR(1000)
);

-- Tabla: item_proveedor
CREATE TABLE item_proveedor (
    item_proveedor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    precio_suministro NUMERIC(10,2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    item_id BIGINT NOT NULL,
    proveedor_id BIGINT NOT NULL REFERENCES proveedor(proveedor_id),
    item_tipo VARCHAR(20) NOT NULL CHECK (item_tipo IN ('INGREDIENTE','INSUMO'))
);

-- Tabla: orden_compra
CREATE TABLE orden_compra (
    orden_compra_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT NOT NULL REFERENCES proveedor(proveedor_id),
    codigo VARCHAR(40) NOT NULL UNIQUE,
    estado VARCHAR(40) NOT NULL CHECK (estado IN ('BORRADOR','ENVIADA','RECIBIDA_PARCIAL','RECIBIDA','CANCELADA')),
    fecha_emision TIMESTAMPTZ DEFAULT NOW(),
    fecha_entrega_esperada TIMESTAMPTZ,
    fecha_entrega_real TIMESTAMPTZ,
    total_estimado NUMERIC(12,2),
    observaciones TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0
);

-- Tabla: orden_compra_detalle
CREATE TABLE orden_compra_detalle (
    orden_compra_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_compra_id BIGINT NOT NULL REFERENCES orden_compra(orden_compra_id) ON DELETE CASCADE,
    item_tipo VARCHAR(40) NOT NULL CHECK (item_tipo IN ('INGREDIENTE','INSUMO')),
    item_id BIGINT NOT NULL,
    item_nombre VARCHAR(160) NOT NULL,
    item_codigo VARCHAR(40) NOT NULL,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12,4),
    subtotal NUMERIC(12,2),
    cantidad_recibida INTEGER NOT NULL DEFAULT 0 CHECK (cantidad_recibida >= 0),
    observaciones TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Tabla: documento_compra
CREATE TABLE documento_compra (
    documento_compra_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_compra_id BIGINT NOT NULL REFERENCES orden_compra(orden_compra_id),
    proveedor_id BIGINT NOT NULL REFERENCES proveedor(proveedor_id),
    numero_documento VARCHAR(60) NOT NULL UNIQUE,
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('BORRADOR','REGISTRADO','ANULADO')),
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
    impuesto NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (impuesto >= 0),
    total NUMERIC(12,2) NOT NULL CHECK (total > 0),
    observaciones TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_documento_compra_orden UNIQUE (orden_compra_id)
);

-- Tabla: documento_pagar
CREATE TABLE documento_pagar (
    documento_pagar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_compra_id BIGINT NOT NULL UNIQUE REFERENCES documento_compra(documento_compra_id),
    proveedor_id BIGINT NOT NULL REFERENCES proveedor(proveedor_id),
    codigo VARCHAR(60) NOT NULL UNIQUE,
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('PENDIENTE','PAGADO_PARCIAL','PAGADO','ANULADO')),
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_vencimiento TIMESTAMPTZ,
    total NUMERIC(12,2) NOT NULL CHECK (total > 0),
    saldo NUMERIC(12,2) NOT NULL CHECK (saldo >= 0),
    observaciones TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_documento_pagar_saldo_total CHECK (saldo <= total)
);

-- Tabla: pago_proveedor
CREATE TABLE pago_proveedor (
    pago_proveedor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT NOT NULL REFERENCES proveedor(proveedor_id),
    codigo VARCHAR(60) NOT NULL UNIQUE,
    fecha_pago TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    monto_total NUMERIC(12,2) NOT NULL CHECK (monto_total > 0),
    medio_pago VARCHAR(40),
    referencia_pago VARCHAR(120),
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('REGISTRADO','ANULADO')),
    observaciones TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0
);

-- Tabla: pago_proveedor_aplicacion
CREATE TABLE pago_proveedor_aplicacion (
    pago_proveedor_aplicacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_proveedor_id BIGINT NOT NULL REFERENCES pago_proveedor(pago_proveedor_id) ON DELETE CASCADE,
    documento_pagar_id BIGINT NOT NULL REFERENCES documento_pagar(documento_pagar_id),
    monto_aplicado NUMERIC(12,2) NOT NULL CHECK (monto_aplicado > 0),
    saldo_anterior NUMERIC(12,2) NOT NULL CHECK (saldo_anterior >= 0),
    saldo_posterior NUMERIC(12,2) NOT NULL CHECK (saldo_posterior >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_pago_proveedor_aplicacion_saldo CHECK (saldo_posterior <= saldo_anterior)
);

-- Tabla: categoria_producto
CREATE TABLE categoria_producto (
    categoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    orden_visual INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

-- Tabla: producto
CREATE TABLE producto (
    producto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    precio_base NUMERIC(10,2) NOT NULL,
    publicado BOOLEAN NOT NULL DEFAULT FALSE,
    requiere_cotizacion BOOLEAN NOT NULL DEFAULT FALSE,
    categoria_id BIGINT NOT NULL REFERENCES categoria_producto(categoria_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    slug VARCHAR(160) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    receta_json TEXT
);

-- Tabla: receta
CREATE TABLE receta (
    receta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    costo_estimado NUMERIC(10,4),
    es_activa BOOLEAN NOT NULL DEFAULT TRUE,
    rendimiento_base NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by_user_id BIGINT REFERENCES usuario_sistema(usuario_id),
    producto_id BIGINT REFERENCES producto(producto_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    nombre VARCHAR(160) NOT NULL,
    observaciones VARCHAR(255)
);

-- Tabla: detalle_receta
CREATE TABLE detalle_receta (
    detalle_receta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_base NUMERIC(10,4) NOT NULL,
    es_para_porcion BOOLEAN NOT NULL DEFAULT FALSE,
    rendimiento_por_unidad NUMERIC(10,4) NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ingrediente_id BIGINT NOT NULL REFERENCES ingrediente(ingrediente_id),
    receta_id BIGINT NOT NULL REFERENCES receta(receta_id) ON DELETE CASCADE,
    observaciones VARCHAR(255)
);

-- Tabla: cliente
CREATE TABLE cliente (
    cliente_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tercero_id BIGINT REFERENCES tercero(tercero_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    telefono VARCHAR(30),
    correo VARCHAR(120),
    nombre_completo VARCHAR(160) NOT NULL,
    observaciones VARCHAR(255)
);

-- Tabla: cotizacion
CREATE TABLE cotizacion (
    cotizacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_estimado NUMERIC(10,2),
    cliente_id BIGINT NOT NULL REFERENCES cliente(cliente_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    origen VARCHAR(20) NOT NULL CHECK (origen IN ('PUBLICO','INTERNO')),
    estado_cotizacion VARCHAR(40) NOT NULL CHECK (estado_cotizacion IN ('PENDIENTE','APROBADA','RECHAZADA','CONVERTIDA')),
    codigo VARCHAR(50) NOT NULL UNIQUE,
    observaciones VARCHAR(255)
);

-- Tabla: cotizacion_detalle
CREATE TABLE cotizacion_detalle (
    cotizacion_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INTEGER NOT NULL,
    precio_estimado NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    cotizacion_id BIGINT NOT NULL REFERENCES cotizacion(cotizacion_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    producto_id BIGINT REFERENCES producto(producto_id),
    descripcion_item VARCHAR(255) NOT NULL,
    notas VARCHAR(255)
);

-- Tabla: pedido
CREATE TABLE pedido (
    pedido_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_estimado NUMERIC(10,2),
    cliente_id BIGINT NOT NULL REFERENCES cliente(cliente_id),
    cotizacion_id BIGINT UNIQUE REFERENCES cotizacion(cotizacion_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_entrega_estimada TIMESTAMPTZ NOT NULL,
    fecha_entrega_real TIMESTAMPTZ,
    fecha_pedido TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    origen VARCHAR(20) NOT NULL CHECK (origen IN ('PUBLICO','INTERNO')),
    prioridad VARCHAR(20) NOT NULL CHECK (prioridad IN ('NORMAL','URGENTE')),
    estado_pedido VARCHAR(40) NOT NULL CHECK (estado_pedido IN ('REGISTRADO','EN_PREPARACION','LISTO','ENTREGADO','CANCELADO')),
    codigo VARCHAR(50) NOT NULL UNIQUE,
    observaciones VARCHAR(255)
);

-- Tabla: pedido_detalle
CREATE TABLE pedido_detalle (
    pedido_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    pedido_id BIGINT NOT NULL REFERENCES pedido(pedido_id),
    producto_id BIGINT NOT NULL REFERENCES producto(producto_id),
    descripcion_item VARCHAR(255) NOT NULL,
    notas VARCHAR(255)
);

-- Tabla: documento_cobrar
CREATE TABLE documento_cobrar (
    documento_cobrar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES cliente(cliente_id),
    pedido_id BIGINT UNIQUE REFERENCES pedido(pedido_id),
    codigo VARCHAR(60) NOT NULL UNIQUE,
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('PENDIENTE','PARCIAL','PAGADO','ANULADO')),
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_vencimiento TIMESTAMPTZ,
    total NUMERIC(12,2) NOT NULL CHECK (total > 0),
    saldo NUMERIC(12,2) NOT NULL CHECK (saldo >= 0),
    observaciones TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_documento_cobrar_saldo_total CHECK (saldo <= total)
);

-- Tabla: cobranza
CREATE TABLE cobranza (
    cobranza_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES cliente(cliente_id),
    codigo VARCHAR(60) NOT NULL UNIQUE,
    fecha_cobranza TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    monto_total NUMERIC(12,2) NOT NULL CHECK (monto_total > 0),
    medio_pago VARCHAR(40),
    referencia_pago VARCHAR(120),
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('REGISTRADA','ANULADA')),
    observaciones TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0
);

-- Tabla: cobranza_detalle
CREATE TABLE cobranza_detalle (
    cobranza_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cobranza_id BIGINT NOT NULL REFERENCES cobranza(cobranza_id) ON DELETE CASCADE,
    documento_cobrar_id BIGINT NOT NULL REFERENCES documento_cobrar(documento_cobrar_id),
    monto_aplicado NUMERIC(12,2) NOT NULL CHECK (monto_aplicado > 0),
    saldo_anterior NUMERIC(12,2) NOT NULL CHECK (saldo_anterior >= 0),
    saldo_posterior NUMERIC(12,2) NOT NULL CHECK (saldo_posterior >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_cobranza_detalle_saldo CHECK (saldo_posterior <= saldo_anterior)
);


-- Tabla: produccion
CREATE TABLE produccion (
    produccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_finalizacion TIMESTAMPTZ,
    fecha_inicio TIMESTAMPTZ,
    pedido_id BIGINT NOT NULL UNIQUE REFERENCES pedido(pedido_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    prioridad_produccion VARCHAR(20) NOT NULL CHECK (prioridad_produccion IN ('NORMAL','URGENTE')),
    estado_produccion VARCHAR(40) NOT NULL CHECK (estado_produccion IN ('PENDIENTE','PREPARACION','DECORACION','EMPAQUE','FINALIZADO','CANCELADO')),
    observaciones_produccion VARCHAR(255)
);

-- Tabla: archivo_recurso
CREATE TABLE archivo_recurso (
    archivo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_por_usuario_id BIGINT REFERENCES usuario_sistema(usuario_id),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_expiracion TIMESTAMPTZ,
    tamano_bytes BIGINT NOT NULL,
    extension VARCHAR(20),
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('DISPONIBLE','EXPIRADO','ELIMINADO')),
    origen_modulo VARCHAR(40) NOT NULL,
    tipo_archivo VARCHAR(40) NOT NULL,
    codigo_archivo VARCHAR(80) NOT NULL UNIQUE,
    mime_type VARCHAR(120) NOT NULL,
    checksum VARCHAR(128),
    ruta_relativa VARCHAR(500) NOT NULL,
    nombre_fisico VARCHAR(255) NOT NULL,
    nombre_original VARCHAR(255) NOT NULL
);

-- Tabla: job_reporte
CREATE TABLE job_reporte (
    job_reporte_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intentos SMALLINT NOT NULL DEFAULT 0,
    archivo_id BIGINT REFERENCES archivo_recurso(archivo_id),
    fecha_fin TIMESTAMPTZ,
    fecha_inicio TIMESTAMPTZ,
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    solicitado_por_usuario_id BIGINT REFERENCES usuario_sistema(usuario_id),
    version BIGINT NOT NULL DEFAULT 0,
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('PENDIENTE','EN_PROCESO','COMPLETADO','ERROR','CANCELADO','EXPIRADO')),
    tipo_reporte VARCHAR(60) NOT NULL CHECK (tipo_reporte IN ('RESUMEN_NEGOCIO','COLA_PRODUCCION')),
    codigo_job VARCHAR(80) NOT NULL UNIQUE,
    request_id VARCHAR(120),
    mensaje_error VARCHAR(255),
    parametros_json JSONB NOT NULL DEFAULT '{}'
);

-- Tabla: notificacion
CREATE TABLE notificacion (
    notificacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_lectura TIMESTAMPTZ,
    usuario_destino_id BIGINT NOT NULL REFERENCES usuario_sistema(usuario_id),
    prioridad VARCHAR(20) NOT NULL CHECK (prioridad IN ('BAJA','MEDIA','ALTA')),
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('NO_LEIDA','LEIDA','ARCHIVADA')),
    modulo VARCHAR(40) NOT NULL,
    referencia_tipo VARCHAR(40),
    tipo_notificacion VARCHAR(60) NOT NULL,
    referencia_id VARCHAR(80),
    titulo VARCHAR(160) NOT NULL,
    mensaje VARCHAR(255) NOT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'
);

-- Tabla: auditoria_evento
CREATE TABLE auditoria_evento (
    auditoria_evento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_usuario_id BIGINT REFERENCES usuario_sistema(usuario_id),
    fecha_evento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modulo VARCHAR(40) NOT NULL,
    ip_origen VARCHAR(64),
    accion VARCHAR(80) NOT NULL,
    actor_rol VARCHAR(80),
    codigo_evento VARCHAR(80) NOT NULL,
    entidad VARCHAR(80) NOT NULL,
    entidad_id VARCHAR(80) NOT NULL,
    request_id VARCHAR(120),
    motivo VARCHAR(255),
    valor_anterior_json JSONB,
    valor_nuevo_json JSONB
);

-- Tabla: inventario_movimiento
CREATE TABLE inventario_movimiento (
    inventario_movimiento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad NUMERIC(10,3) NOT NULL,
    saldo_anterior NUMERIC(10,3),
    saldo_posterior NUMERIC(10,3) NOT NULL,
    fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    item_id BIGINT NOT NULL,
    registrado_por_user_id BIGINT REFERENCES usuario_sistema(usuario_id),
    item_tipo VARCHAR(20) NOT NULL,
    tipo_movimiento VARCHAR(30) NOT NULL,
    referencia_tipo VARCHAR(40),
    referencia_id VARCHAR(80),
    motivo_salida VARCHAR(100),
    observaciones VARCHAR(255)
);

-- Tabla: consumo_material_produccion
CREATE TABLE consumo_material_produccion (
    consumo_material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produccion_id BIGINT NOT NULL REFERENCES produccion(produccion_id),
    pedido_detalle_id BIGINT NOT NULL REFERENCES pedido_detalle(pedido_detalle_id),
    receta_id BIGINT REFERENCES receta(receta_id),
    detalle_receta_id BIGINT REFERENCES detalle_receta(detalle_receta_id),
    ingrediente_id BIGINT NOT NULL REFERENCES ingrediente(ingrediente_id),
    cantidad_teorica NUMERIC(12,4) NOT NULL CHECK (cantidad_teorica > 0),
    cantidad_consumida NUMERIC(12,4) NOT NULL CHECK (cantidad_consumida > 0),
    costo_unitario NUMERIC(12,4),
    costo_total NUMERIC(12,4),
    movimiento_inventario_id BIGINT REFERENCES inventario_movimiento(inventario_movimiento_id),
    observaciones VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_consumo_material_produccion ON consumo_material_produccion (produccion_id, created_at);
CREATE INDEX idx_consumo_material_movimiento ON consumo_material_produccion (movimiento_inventario_id);

-- Tabla: lote_produccion
CREATE TABLE lote_produccion (
    lote_produccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produccion_id BIGINT NOT NULL REFERENCES produccion(produccion_id),
    pedido_detalle_id BIGINT NOT NULL REFERENCES pedido_detalle(pedido_detalle_id),
    producto_id BIGINT NOT NULL REFERENCES producto(producto_id),
    codigo_lote VARCHAR(80) NOT NULL UNIQUE,
    fecha_produccion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cantidad_producida NUMERIC(12,4) NOT NULL CHECK (cantidad_producida > 0),
    cantidad_disponible NUMERIC(12,4) NOT NULL CHECK (cantidad_disponible >= 0),
    costo_total_estimado NUMERIC(12,4),
    estado VARCHAR(30) NOT NULL DEFAULT 'DISPONIBLE' CHECK (estado IN ('DISPONIBLE','CONSUMIDO','VENDIDO','VENCIDO','ANULADO')),
    observaciones VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_lote_produccion ON lote_produccion (produccion_id, created_at);
CREATE INDEX idx_lote_producto_estado ON lote_produccion (producto_id, estado);

-- Tabla: entrada_producto_terminado
CREATE TABLE entrada_producto_terminado (
    entrada_producto_terminado_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_produccion_id BIGINT NOT NULL REFERENCES lote_produccion(lote_produccion_id),
    produccion_id BIGINT NOT NULL REFERENCES produccion(produccion_id),
    producto_id BIGINT NOT NULL REFERENCES producto(producto_id),
    cantidad NUMERIC(12,4) NOT NULL CHECK (cantidad > 0),
    costo_total_estimado NUMERIC(12,4),
    observaciones VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_entrada_producto_terminado ON entrada_producto_terminado (produccion_id, created_at);


-- Tabla: merma_produccion
CREATE TABLE merma_produccion (
    merma_produccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produccion_id BIGINT REFERENCES produccion(produccion_id),
    producto_id BIGINT REFERENCES producto(producto_id),
    ingrediente_id BIGINT REFERENCES ingrediente(ingrediente_id),
    tipo_merma VARCHAR(40) NOT NULL DEFAULT 'OTRO',
    cantidad NUMERIC(12,4) NOT NULL CHECK (cantidad > 0),
    costo_estimado NUMERIC(12,4),
    motivo VARCHAR(500) NOT NULL,
    movimiento_inventario_id BIGINT REFERENCES inventario_movimiento(inventario_movimiento_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_merma_produccion ON merma_produccion (produccion_id, created_at);

-- Tabla: caso_uso_modulo
CREATE TABLE caso_uso_modulo (
    caso_uso_modulo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    grupo VARCHAR(80) NOT NULL DEFAULT 'OPERACION',
    orden_visual INTEGER NOT NULL DEFAULT 999,
    descripcion TEXT
);

-- Tabla: caso_uso_operativo
CREATE TABLE caso_uso_operativo (
    caso_uso_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    version_flujo INTEGER NOT NULL DEFAULT 1,
    actualizado_en TIMESTAMPTZ,
    modulo VARCHAR(80) NOT NULL REFERENCES caso_uso_modulo(codigo),
    codigo VARCHAR(40) NOT NULL UNIQUE,
    titulo VARCHAR(180) NOT NULL,
    actor_principal VARCHAR(80),
    punto_inicio VARCHAR(220),
    orden_visual INTEGER NOT NULL DEFAULT 999,
    estado VARCHAR(40) NOT NULL DEFAULT 'LISTO' CHECK (estado IN ('BORRADOR','LISTO','REVISAR')),
    objetivo TEXT
);

-- Tabla: paso_caso_uso
CREATE TABLE paso_caso_uso (
    paso_caso_uso_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caso_uso_id BIGINT NOT NULL REFERENCES caso_uso_operativo(caso_uso_id) ON DELETE CASCADE,
    numero INTEGER NOT NULL CHECK (numero > 0),
    descripcion TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_paso_caso_uso_numero UNIQUE (caso_uso_id, numero)
);

-- =============================================================================
-- SECCIÓN 3: ÍNDICES ADICIONALES
-- =============================================================================
CREATE INDEX idx_producto_categoria ON producto(categoria_id);
CREATE INDEX idx_producto_activo ON producto(activo);
CREATE INDEX idx_pedido_estado ON pedido(estado_pedido);
CREATE INDEX idx_pedido_cliente ON pedido(cliente_id);
CREATE INDEX idx_cotizacion_estado ON cotizacion(estado_cotizacion);
CREATE INDEX idx_produccion_estado ON produccion(estado_produccion);
CREATE INDEX idx_ingrediente_codigo ON ingrediente(codigo);
CREATE INDEX idx_insumo_codigo ON insumo(codigo);
CREATE INDEX idx_proveedor_codigo ON proveedor(codigo);
CREATE INDEX idx_orden_compra_estado ON orden_compra(estado, created_at DESC);
CREATE INDEX idx_orden_compra_proveedor ON orden_compra(proveedor_id, estado);
CREATE INDEX idx_orden_compra_detalle_orden ON orden_compra_detalle(orden_compra_id);
CREATE INDEX idx_documento_compra_orden ON documento_compra(orden_compra_id);
CREATE INDEX idx_documento_compra_proveedor ON documento_compra(proveedor_id, estado);
CREATE INDEX idx_documento_pagar_proveedor ON documento_pagar(proveedor_id, estado);
CREATE INDEX idx_documento_pagar_estado ON documento_pagar(estado, fecha_vencimiento);
CREATE INDEX idx_documento_cobrar_cliente ON documento_cobrar(cliente_id, estado);
CREATE INDEX idx_documento_cobrar_estado ON documento_cobrar(estado, fecha_vencimiento);
CREATE INDEX idx_cobranza_cliente_fecha ON cobranza(cliente_id, fecha_cobranza DESC);
CREATE INDEX idx_cobranza_detalle_documento ON cobranza_detalle(documento_cobrar_id);
CREATE INDEX idx_pago_proveedor_proveedor_fecha ON pago_proveedor(proveedor_id, fecha_pago DESC);
CREATE INDEX idx_pago_proveedor_aplicacion_documento ON pago_proveedor_aplicacion(documento_pagar_id);
CREATE INDEX idx_notificacion_usuario ON notificacion(usuario_destino_id);
CREATE INDEX idx_archivo_estado ON archivo_recurso(estado);
CREATE INDEX idx_caso_uso_modulo_orden ON caso_uso_modulo(activo, orden_visual, codigo);
CREATE INDEX idx_caso_uso_operativo_hub ON caso_uso_operativo(modulo, activo, orden_visual, codigo);
CREATE INDEX idx_paso_caso_uso_caso_numero ON paso_caso_uso(caso_uso_id, numero);

