-- =============================================================================
-- PASTELERÍA - SCRIPT MAESTRO COMPLETO (Schema JPA + Seeds)
-- Versión: 4.0 - Generado desde Entidades JPA
-- Fecha: 2026-03-20
-- 
-- Este script garantiza 100% compatibilidad entre el código Java y la base de datos.
-- Fue generado automáticamente desde las entidades JPA de Hibernate.
-- =============================================================================

-- =============================================================================
-- SECCIÓN 1: LIMPIEZA
-- =============================================================================
DROP TABLE IF EXISTS inventario_movimiento CASCADE;
DROP TABLE IF EXISTS item_proveedor CASCADE;
DROP TABLE IF EXISTS proveedor CASCADE;
DROP TABLE IF EXISTS insumo CASCADE;
DROP TABLE IF EXISTS ingrediente CASCADE;
DROP TABLE IF EXISTS umedida CASCADE;
DROP TABLE IF EXISTS archivo_recurso CASCADE;
DROP TABLE IF EXISTS auditoria_evento CASCADE;
DROP TABLE IF EXISTS categoria_producto CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS cotizacion_detalle CASCADE;
DROP TABLE IF EXISTS cotizacion CASCADE;
DROP TABLE IF EXISTS detalle_receta CASCADE;
DROP TABLE IF EXISTS receta CASCADE;
DROP TABLE IF EXISTS notificacion CASCADE;
DROP TABLE IF EXISTS job_reporte CASCADE;
DROP TABLE IF EXISTS pedido_detalle CASCADE;
DROP TABLE IF EXISTS pedido CASCADE;
DROP TABLE IF EXISTS produccion CASCADE;
DROP TABLE IF EXISTS producto CASCADE;
DROP TABLE IF EXISTS rol_usuario CASCADE;
DROP TABLE IF EXISTS usuario_sistema CASCADE;

-- =============================================================================
-- SECCIÓN 2: SCHEMA (Generado desde JPA Entities)
-- =============================================================================

-- Tabla: rol_usuario
CREATE TABLE rol_usuario (
    rol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    codigo VARCHAR(40) NOT NULL UNIQUE CHECK (codigo IN ('ADMIN','ATENCION','PRODUCCION')),
    nombre_rol VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

-- Tabla: usuario_sistema
CREATE TABLE usuario_sistema (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rol_id BIGINT NOT NULL REFERENCES rol_usuario(rol_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    apellidos VARCHAR(120) NOT NULL,
    correo VARCHAR(120),
    nombre_usuario VARCHAR(120) NOT NULL UNIQUE,
    nombres VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);

-- Tabla: umedida
CREATE TABLE umedida (
    umedida_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    decimales SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    abreviatura VARCHAR(10) NOT NULL,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('PESO','VOLUMEN','UNIDAD','ENVASE')),
    nombre VARCHAR(60) NOT NULL
);

-- Tabla: ingrediente
CREATE TABLE ingrediente (
    ingrediente_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    costo_referencial NUMERIC(10,2),
    stock_actual NUMERIC(12,4) DEFAULT 0,
    stock_minimo NUMERIC(12,4),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    umedida_id BIGINT NOT NULL REFERENCES umedida(umedida_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500)
);

-- Tabla: insumo
CREATE TABLE insumo (
    insumo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    costo_referencial NUMERIC(10,2),
    stock_actual NUMERIC(12,4) DEFAULT 0,
    stock_minimo NUMERIC(12,4),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    umedida_id BIGINT NOT NULL REFERENCES umedida(umedida_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500)
);

-- Tabla: proveedor
CREATE TABLE proveedor (
    proveedor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    telefono VARCHAR(30),
    codigo VARCHAR(40) NOT NULL UNIQUE,
    correo VARCHAR(120),
    nombre VARCHAR(160) NOT NULL,
    direccion VARCHAR(500),
    observaciones VARCHAR(1000)
);

-- Tabla: item_proveedor
CREATE TABLE item_proveedor (
    item_proveedor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    precio_suministro NUMERIC(10,2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    item_id BIGINT NOT NULL,
    proveedor_id BIGINT NOT NULL REFERENCES proveedor(proveedor_id),
    item_tipo VARCHAR(20) NOT NULL CHECK (item_tipo IN ('INGREDIENTE','INSUMO'))
);

-- Tabla: categoria_producto
CREATE TABLE categoria_producto (
    categoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    orden_visual INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

-- Tabla: producto
CREATE TABLE producto (
    producto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    precio_base NUMERIC(10,2) NOT NULL,
    publicado BOOLEAN NOT NULL DEFAULT FALSE,
    requiere_cotizacion BOOLEAN NOT NULL DEFAULT FALSE,
    categoria_id BIGINT NOT NULL REFERENCES categoria_producto(categoria_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    slug VARCHAR(160) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    receta_json JSONB
);

-- Tabla: receta
CREATE TABLE receta (
    receta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    costo_estimado NUMERIC(10,4),
    es_activa BOOLEAN NOT NULL DEFAULT TRUE,
    rendimiento_base NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by_user_id BIGINT REFERENCES usuario_sistema(usuario_id),
    producto_id BIGINT REFERENCES producto(producto_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    nombre VARCHAR(160) NOT NULL,
    observaciones VARCHAR(255)
);

-- Tabla: detalle_receta
CREATE TABLE detalle_receta (
    detalle_receta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_base NUMERIC(10,4) NOT NULL,
    es_para_porcion BOOLEAN NOT NULL DEFAULT FALSE,
    rendimiento_por_unidad NUMERIC(10,4) NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ingrediente_id BIGINT NOT NULL REFERENCES ingrediente(ingrediente_id),
    receta_id BIGINT NOT NULL REFERENCES receta(receta_id) ON DELETE CASCADE,
    observaciones VARCHAR(255)
);

-- Tabla: cliente
CREATE TABLE cliente (
    cliente_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    telefono VARCHAR(30),
    correo VARCHAR(120),
    nombre_completo VARCHAR(160) NOT NULL,
    observaciones VARCHAR(255)
);

-- Tabla: cotizacion
CREATE TABLE cotizacion (
    cotizacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_estimado NUMERIC(10,2),
    cliente_id BIGINT NOT NULL REFERENCES cliente(cliente_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    origen VARCHAR(20) NOT NULL CHECK (origen IN ('PUBLICO','INTERNO')),
    estado_cotizacion VARCHAR(40) NOT NULL CHECK (estado_cotizacion IN ('PENDIENTE','APROBADA','RECHAZADA','CONVERTIDA')),
    codigo VARCHAR(50) NOT NULL UNIQUE,
    observaciones VARCHAR(255)
);

-- Tabla: cotizacion_detalle
CREATE TABLE cotizacion_detalle (
    cotizacion_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INTEGER NOT NULL,
    precio_estimado NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    cotizacion_id BIGINT NOT NULL REFERENCES cotizacion(cotizacion_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    producto_id BIGINT REFERENCES producto(producto_id),
    descripcion_item VARCHAR(255) NOT NULL,
    notas VARCHAR(255)
);

-- Tabla: pedido
CREATE TABLE pedido (
    pedido_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_estimado NUMERIC(10,2),
    cliente_id BIGINT NOT NULL REFERENCES cliente(cliente_id),
    cotizacion_id BIGINT UNIQUE REFERENCES cotizacion(cotizacion_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_entrega_estimada TIMESTAMPTZ NOT NULL,
    fecha_entrega_real TIMESTAMPTZ,
    fecha_pedido TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    origen VARCHAR(20) NOT NULL CHECK (origen IN ('PUBLICO','INTERNO')),
    prioridad VARCHAR(20) NOT NULL CHECK (prioridad IN ('NORMAL','URGENTE')),
    estado_pedido VARCHAR(40) NOT NULL CHECK (estado_pedido IN ('REGISTRADO','EN_PREPARACION','LISTO','ENTREGADO','CANCELADO')),
    codigo VARCHAR(50) NOT NULL UNIQUE,
    observaciones VARCHAR(255)
);

-- Tabla: pedido_detalle
CREATE TABLE pedido_detalle (
    pedido_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    pedido_id BIGINT NOT NULL REFERENCES pedido(pedido_id),
    producto_id BIGINT NOT NULL REFERENCES producto(producto_id),
    descripcion_item VARCHAR(255) NOT NULL,
    notas VARCHAR(255)
);

-- Tabla: produccion
CREATE TABLE produccion (
    produccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_finalizacion TIMESTAMPTZ,
    fecha_inicio TIMESTAMPTZ,
    pedido_id BIGINT NOT NULL UNIQUE REFERENCES pedido(pedido_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    prioridad_produccion VARCHAR(20) NOT NULL CHECK (prioridad_produccion IN ('NORMAL','URGENTE')),
    estado_produccion VARCHAR(40) NOT NULL CHECK (estado_produccion IN ('PENDIENTE','PREPARACION','DECORACION','EMPAQUE','FINALIZADO')),
    observaciones_produccion VARCHAR(255)
);

-- Tabla: archivo_recurso
CREATE TABLE archivo_recurso (
    archivo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_por_usuario_id BIGINT REFERENCES usuario_sistema(usuario_id),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_expiracion TIMESTAMPTZ,
    tamano_bytes BIGINT NOT NULL,
    extension VARCHAR(20),
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('DISPONIBLE','EXPIRADO','ELIMINADO')),
    origen_modulo VARCHAR(40) NOT NULL,
    tipo_archivo VARCHAR(40) NOT NULL,
    codigo_archivo VARCHAR(80) NOT NULL UNIQUE,
    mime_type VARCHAR(120) NOT NULL,
    checksum VARCHAR(128),
    ruta_relativa VARCHAR(500) NOT NULL,
    nombre_fisico VARCHAR(255) NOT NULL,
    nombre_original VARCHAR(255) NOT NULL
);

-- Tabla: job_reporte
CREATE TABLE job_reporte (
    job_reporte_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intentos SMALLINT NOT NULL DEFAULT 0,
    archivo_id BIGINT REFERENCES archivo_recurso(archivo_id),
    fecha_fin TIMESTAMPTZ,
    fecha_inicio TIMESTAMPTZ,
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    solicitado_por_usuario_id BIGINT REFERENCES usuario_sistema(usuario_id),
    version BIGINT NOT NULL DEFAULT 0,
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('PENDIENTE','EN_PROCESO','COMPLETADO','ERROR','CANCELADO','EXPIRADO')),
    tipo_reporte VARCHAR(60) NOT NULL CHECK (tipo_reporte IN ('RESUMEN_NEGOCIO','COLA_PRODUCCION')),
    codigo_job VARCHAR(80) NOT NULL UNIQUE,
    request_id VARCHAR(120),
    mensaje_error VARCHAR(255),
    parametros_json JSONB NOT NULL DEFAULT '{}'
);

-- Tabla: notificacion
CREATE TABLE notificacion (
    notificacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_lectura TIMESTAMPTZ,
    usuario_destino_id BIGINT NOT NULL REFERENCES usuario_sistema(usuario_id),
    prioridad VARCHAR(20) NOT NULL CHECK (prioridad IN ('BAJA','MEDIA','ALTA')),
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('NO_LEIDA','LEIDA','ARCHIVADA')),
    modulo VARCHAR(40) NOT NULL,
    referencia_tipo VARCHAR(40),
    tipo_notificacion VARCHAR(60) NOT NULL,
    referencia_id VARCHAR(80),
    titulo VARCHAR(160) NOT NULL,
    mensaje VARCHAR(255) NOT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'
);

-- Tabla: auditoria_evento
CREATE TABLE auditoria_evento (
    auditoria_evento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_usuario_id BIGINT REFERENCES usuario_sistema(usuario_id),
    fecha_evento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modulo VARCHAR(40) NOT NULL,
    ip_origen VARCHAR(64),
    accion VARCHAR(80) NOT NULL,
    actor_rol VARCHAR(80),
    codigo_evento VARCHAR(80) NOT NULL,
    entidad VARCHAR(80) NOT NULL,
    entidad_id VARCHAR(80) NOT NULL,
    request_id VARCHAR(120),
    motivo VARCHAR(255),
    valor_anterior_json JSONB,
    valor_nuevo_json JSONB
);

-- Tabla: inventario_movimiento
CREATE TABLE inventario_movimiento (
    inventario_movimiento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad NUMERIC(10,3) NOT NULL,
    saldo_posterior NUMERIC(10,3) NOT NULL,
    fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    item_id BIGINT NOT NULL,
    registrado_por_user_id BIGINT REFERENCES usuario_sistema(usuario_id),
    item_tipo VARCHAR(20) NOT NULL,
    tipo_movimiento VARCHAR(30) NOT NULL,
    referencia_tipo VARCHAR(40),
    referencia_id VARCHAR(80),
    motivo_salida VARCHAR(100),
    observaciones VARCHAR(255)
);

-- =============================================================================
-- SECCIÓN 3: ÍNDICES ADICIONALES
-- =============================================================================
CREATE INDEX idx_producto_categoria ON producto(categoria_id);
CREATE INDEX idx_producto_activo ON producto(activo);
CREATE INDEX idx_pedido_estado ON pedido(estado_pedido);
CREATE INDEX idx_pedido_cliente ON pedido(cliente_id);
CREATE INDEX idx_cotizacion_estado ON cotizacion(estado_cotizacion);
CREATE INDEX idx_produccion_estado ON produccion(estado_produccion);
CREATE INDEX idx_ingrediente_codigo ON ingrediente(codigo);
CREATE INDEX idx_insumo_codigo ON insumo(codigo);
CREATE INDEX idx_proveedor_codigo ON proveedor(codigo);
CREATE INDEX idx_notificacion_usuario ON notificacion(usuario_destino_id);
CREATE INDEX idx_archivo_estado ON archivo_recurso(estado);

-- =============================================================================
-- SECCIÓN 4: SEEDS (Datos Iniciales)
-- =============================================================================

-- Roles del sistema
INSERT INTO rol_usuario (codigo, nombre_rol, descripcion, activo, created_at) VALUES
('ADMIN', 'Administrador', 'Control total del sistema', true, NOW()),
('ATENCION', 'Atención al Cliente', 'Gestión de pedidos y cotizaciones', true, NOW()),
('PRODUCCION', 'Producción', 'Gestión de órdenes de producción', true, NOW());

-- Usuario administrador (password: admin123)
INSERT INTO usuario_sistema (
    nombre_usuario, nombres, apellidos, password_hash, correo, 
    rol_id, activo, created_at, updated_at, version
) VALUES (
    'admin', 'Administrador', 'Sistema', 
    '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqQzdwEOK/OtMz0HgEpkDzQJXTP6C',
    'admin@pasteleria.com',
    (SELECT rol_id FROM rol_usuario WHERE codigo = 'ADMIN'),
    true, NOW(), NOW(), 0
);

-- Unidades de medida
INSERT INTO umedida (codigo, nombre, abreviatura, tipo, decimales, activo, created_at, updated_at, version) VALUES
('KG', 'Kilogramo', 'kg', 'PESO', 3, true, NOW(), NOW(), 0),
('GR', 'Gramo', 'g', 'PESO', 2, true, NOW(), NOW(), 0),
('LT', 'Litro', 'L', 'VOLUMEN', 3, true, NOW(), NOW(), 0),
('ML', 'Mililitro', 'ml', 'VOLUMEN', 2, true, NOW(), NOW(), 0),
('UN', 'Unidad', 'und', 'UNIDAD', 0, true, NOW(), NOW(), 0),
('CJA', 'Caja', 'cja', 'ENVASE', 0, true, NOW(), NOW(), 0);

-- Categorías de productos
INSERT INTO categoria_producto (codigo, nombre, descripcion, orden_visual, activo, created_at, updated_at, version) VALUES
('TORTAS', 'Tortas', 'Tortas para toda ocasión', 1, true, NOW(), NOW(), 0),
('CUPCAKES', 'Cupcakes', 'Cupcakes decorados', 2, true, NOW(), NOW(), 0),
('GALLETAS', 'Galletas', 'Galletas artesanales', 3, true, NOW(), NOW(), 0),
('POSTRES', 'Postres', 'Postres individuales', 4, true, NOW(), NOW(), 0);

-- Ingredientes base
INSERT INTO ingrediente (codigo, nombre, descripcion, stock_actual, stock_minimo, costo_referencial, umedida_id, activo, created_at, updated_at, version) VALUES
('HAR-0001', 'Harina de trigo', 'Harina todo uso', 50.0000, 10.0000, 2.50, (SELECT umedida_id FROM umedida WHERE codigo = 'KG'), true, NOW(), NOW(), 0),
('AZU-0001', 'Azúcar blanca', 'Azúcar refinada', 25.0000, 5.0000, 3.20, (SELECT umedida_id FROM umedida WHERE codigo = 'KG'), true, NOW(), NOW(), 0),
('MAN-0001', 'Mantequilla', 'Mantequilla sin sal', 10.0000, 2.0000, 8.50, (SELECT umedida_id FROM umedida WHERE codigo = 'KG'), true, NOW(), NOW(), 0),
('HUE-0001', 'Huevos', 'Huevos grandes', 100.0000, 20.0000, 0.25, (SELECT umedida_id FROM umedida WHERE codigo = 'UN'), true, NOW(), NOW(), 0),
('LEV-0001', 'Levadura', 'Levadura fresca', 2.0000, 0.5000, 15.00, (SELECT umedida_id FROM umedida WHERE codigo = 'KG'), true, NOW(), NOW(), 0);

-- Insumos base
INSERT INTO insumo (codigo, nombre, descripcion, stock_actual, stock_minimo, costo_referencial, umedida_id, activo, created_at, updated_at, version) VALUES
('CAJ-0001', 'Caja torta 25cm', 'Caja para tortas de 25cm', 50.0000, 10.0000, 1.50, (SELECT umedida_id FROM umedida WHERE codigo = 'UN'), true, NOW(), NOW(), 0),
('CAJ-0002', 'Caja torta 30cm', 'Caja para tortas de 30cm', 30.0000, 5.0000, 2.00, (SELECT umedida_id FROM umedida WHERE codigo = 'UN'), true, NOW(), NOW(), 0),
('VEL-0001', 'Velas cumpleaños', 'Pack velas de cumpleaños', 100.0000, 20.0000, 0.80, (SELECT umedida_id FROM umedida WHERE codigo = 'UN'), true, NOW(), NOW(), 0);

-- Proveedores
INSERT INTO proveedor (codigo, nombre, direccion, telefono, correo, observaciones, activo, created_at, updated_at, version) VALUES
('PROV-001', 'Distribuidora Alimentos SAC', 'Av. Principal 123', '987654321', 'ventas@distribuidora.com', 'Proveedor principal de harina y azúcar', true, NOW(), NOW(), 0),
('PROV-002', 'Lácteos del Valle', 'Jr. Los Olivos 456', '987123456', 'pedidos@lacteos.com', 'Mantequilla y derivados lácteos', true, NOW(), NOW(), 0);

-- Productos de ejemplo
INSERT INTO producto (codigo, nombre, slug, descripcion, precio_base, categoria_id, activo, publicado, requiere_cotizacion, receta_json, created_at, updated_at, version) VALUES
('TORT-CHOC-01', 'Torta de Chocolate', 'torta-chocolate', 'Deliciosa torta de chocolate', 150.00, (SELECT categoria_id FROM categoria_producto WHERE codigo = 'TORTAS'), true, true, false, '{"ingredientes": [{"ingrediente_id": 1, "cantidad": 0.5}, {"ingrediente_id": 2, "cantidad": 0.3}]}', NOW(), NOW(), 0),
('CUPK-VAIN-01', 'Cupcake Vainilla', 'cupcake-vainilla', 'Cupcake de vainilla', 8.00, (SELECT categoria_id FROM categoria_producto WHERE codigo = 'CUPCAKES'), true, true, false, null, NOW(), NOW(), 0);

-- Clientes de ejemplo
INSERT INTO cliente (nombre_completo, correo, telefono, observaciones, fecha_registro, created_at, updated_at, version) VALUES
('Juan Pérez', 'juan@email.com', '987111222', 'Cliente frecuente', NOW(), NOW(), NOW(), 0),
('María García', 'maria@email.com', '987333444', 'Prefiere entregas en la mañana', NOW(), NOW(), NOW(), 0);

COMMIT;

-- =============================================================================
-- VERIFICACIÓN
-- =============================================================================
SELECT 'Base de datos inicializada correctamente' as estado;
SELECT COUNT(*) as total_tablas FROM information_schema.tables WHERE table_schema = 'public';
SELECT COUNT(*) as total_roles FROM rol_usuario;
SELECT COUNT(*) as total_usuarios FROM usuario_sistema;
SELECT COUNT(*) as total_categorias FROM categoria_producto;
SELECT COUNT(*) as total_ingredientes FROM ingrediente;
SELECT COUNT(*) as total_insumos FROM insumo;
SELECT COUNT(*) as total_productos FROM producto;
SELECT COUNT(*) as total_proveedores FROM proveedor;
