# Configuración local para usar el contenedor Docker de PostgreSQL en puerto 5434
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/pasteleria
    username: postgres
    password: postgres
