spring:
  jpa:
    show-sql: true

logging:
  level:
    com.pasteleria: INFO
    org.springframework.security: INFO

app:
  jwt:
    secret: ${JWT_SECRET:ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ}
