# Configuración local para usar el contenedor Docker de PostgreSQL en puerto 5436
spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/pasteleria
    username: postgres
    password: postgres
