SET client_encoding = 'UTF8';

-- =============================================================================
-- Tanda 7 y 8 - Guia operativa de Pasteleria
-- Crea el backend persistente de flujos consultivos y siembra datos reales.
-- =============================================================================

CREATE TABLE IF NOT EXISTS caso_uso_modulo (
  caso_uso_modulo_id BIGSERIAL PRIMARY KEY,
  codigo VARCHAR(80) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion TEXT,
  grupo VARCHAR(80) NOT NULL DEFAULT 'OPERACION',
  orden_visual INTEGER NOT NULL DEFAULT 999,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS caso_uso_operativo (
  caso_uso_id BIGSERIAL PRIMARY KEY,
  modulo VARCHAR(80) NOT NULL,
  codigo VARCHAR(40) NOT NULL UNIQUE,
  titulo VARCHAR(180) NOT NULL,
  actor_principal VARCHAR(80),
  objetivo TEXT,
  punto_inicio VARCHAR(220),
  orden_visual INTEGER NOT NULL DEFAULT 999,
  estado VARCHAR(40) NOT NULL DEFAULT 'LISTO',
  version_flujo INTEGER NOT NULL DEFAULT 1,
  actualizado_en TIMESTAMPTZ,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_caso_uso_operativo_modulo_codigo FOREIGN KEY (modulo) REFERENCES caso_uso_modulo(codigo),
  CONSTRAINT ck_caso_uso_operativo_estado CHECK (estado IN ('BORRADOR', 'LISTO', 'REVISAR'))
);

CREATE TABLE IF NOT EXISTS paso_caso_uso (
  paso_caso_uso_id BIGSERIAL PRIMARY KEY,
  caso_uso_id BIGINT NOT NULL REFERENCES caso_uso_operativo(caso_uso_id) ON DELETE CASCADE,
  numero INTEGER NOT NULL,
  descripcion TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uq_paso_caso_uso_numero UNIQUE (caso_uso_id, numero),
  CONSTRAINT ck_paso_caso_uso_numero CHECK (numero > 0)
);

CREATE INDEX IF NOT EXISTS idx_caso_uso_modulo_orden ON caso_uso_modulo(activo, orden_visual, codigo);
CREATE INDEX IF NOT EXISTS idx_caso_uso_operativo_hub ON caso_uso_operativo(modulo, activo, orden_visual, codigo);
CREATE INDEX IF NOT EXISTS idx_paso_caso_uso_caso_numero ON paso_caso_uso(caso_uso_id, numero);

INSERT INTO caso_uso_modulo (codigo, nombre, descripcion, grupo, orden_visual, activo, created_at, updated_at, version) VALUES
  ('RESUMEN_DIA', 'Resumen del día', 'Vista inicial para revisar el pulso diario: encargos, producción, avisos y pendientes de mostrador.', 'OPERACION', 1, TRUE, NOW(), NOW(), 0),
  ('CLIENTES', 'Clientes', 'Registro y consulta de clientes que compran en mostrador o solicitan encargos personalizados.', 'COMERCIAL', 2, TRUE, NOW(), NOW(), 0),
  ('CATALOGO', 'Catálogo de productos', 'Administración de productos, precios, disponibilidad y vitrina digital de la pastelería.', 'COMERCIAL', 3, TRUE, NOW(), NOW(), 0),
  ('COTIZACIONES', 'Cotizaciones', 'Preparación de propuestas para tortas, mesas dulces y pedidos especiales antes de confirmarlos.', 'COMERCIAL', 4, TRUE, NOW(), NOW(), 0),
  ('PEDIDOS', 'Pedidos', 'Seguimiento de encargos confirmados desde el registro hasta la entrega o retiro.', 'OPERACION', 5, TRUE, NOW(), NOW(), 0),
  ('PRODUCCION', 'Producción', 'Organización de horneo, relleno, decoración y avance del trabajo interno.', 'OPERACION', 6, TRUE, NOW(), NOW(), 0),
  ('DECORACION_EMPAQUE', 'Decoración y empaque', 'Cierre visual del producto, control de empaque, retiro y entrega final.', 'OPERACION', 7, TRUE, NOW(), NOW(), 0),
  ('ABASTECIMIENTO', 'Abastecimiento', 'Control de insumos, mínimos, reposición y movimientos de entrada o salida.', 'OPERACION', 8, TRUE, NOW(), NOW(), 0),
  ('RECETAS', 'Recetas técnicas', 'Consulta de recetas base, cantidades, rendimiento y notas de preparación.', 'OPERACION', 9, TRUE, NOW(), NOW(), 0),
  ('PROVEEDORES', 'Proveedores', 'Gestión de proveedores, productos ofrecidos y compras pendientes.', 'ADMINISTRACION', 10, TRUE, NOW(), NOW(), 0),
  ('REPORTES', 'Reportes', 'Generación y revisión de reportes para decisiones semanales del negocio.', 'CONTROL', 11, TRUE, NOW(), NOW(), 0),
  ('NOTIFICACIONES', 'Notificaciones', 'Atención de avisos internos sobre pedidos, producción, reportes e inventario.', 'CONTROL', 12, TRUE, NOW(), NOW(), 0),
  ('USUARIOS', 'Usuarios y permisos', 'Administración de accesos según rol: administración, atención y producción.', 'ADMINISTRACION', 13, TRUE, NOW(), NOW(), 0),
  ('GUIA_OPERATIVA', 'Guía operativa', 'Consulta de flujos de trabajo para recordar cómo operar cada área del sistema.', 'CONTROL', 14, TRUE, NOW(), NOW(), 0)
ON CONFLICT (codigo) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  descripcion = EXCLUDED.descripcion,
  grupo = EXCLUDED.grupo,
  orden_visual = EXCLUDED.orden_visual,
  activo = EXCLUDED.activo,
  updated_at = NOW();

INSERT INTO caso_uso_operativo (modulo, codigo, titulo, actor_principal, objetivo, punto_inicio, orden_visual, estado, version_flujo, actualizado_en, activo, created_at, updated_at, version) VALUES
  ('RESUMEN_DIA', 'CU-GO-001', 'Revisar el resumen del día', 'Administrador o encargada de turno', 'Entender en pocos minutos qué se debe atender primero: encargos, producción, avisos y pendientes del local.', 'Haz clic en Resumen desde el menú lateral.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('RESUMEN_DIA', 'CU-GO-002', 'Usar las notificaciones del resumen', 'Administrador o encargada de turno', 'Atender avisos críticos sin revisar módulo por módulo al inicio del turno.', 'Haz clic en el botón Notificaciones del resumen.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('RESUMEN_DIA', 'CU-GO-003', 'Interpretar la meta semanal', 'Administrador', 'Comparar ventas cerradas contra una meta mínima para decidir si hay que impulsar productos o pedidos.', 'Haz clic en Resumen y mira la tarjeta Meta mínima semanal.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('CLIENTES', 'CU-GO-010', 'Registrar cliente de mostrador o encargo', 'Atención al cliente', 'Guardar los datos mínimos de una persona que compra, consulta o solicita una torta personalizada.', 'Haz clic en Clientes desde el menú lateral.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('CLIENTES', 'CU-GO-011', 'Buscar y corregir datos de cliente', 'Atención al cliente', 'Evitar duplicados y mantener información de contacto útil para pedidos y cotizaciones.', 'Haz clic en Clientes y revisa la lista.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('CLIENTES', 'CU-GO-012', 'Usar cliente en cotización o pedido', 'Atención al cliente', 'Relacionar cada venta o propuesta con una persona real para seguimiento y recompra.', 'Empieza desde Clientes, Cotizaciones o Pedidos.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('CATALOGO', 'CU-GO-020', 'Crear producto de catálogo', 'Administrador', 'Agregar un producto nuevo con precio, categoría, imagen y estado de publicación.', 'Haz clic en Productos desde el menú lateral.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('CATALOGO', 'CU-GO-021', 'Editar producto y descargar receta PDF', 'Administrador o producción', 'Actualizar información de producto y bajar la receta técnica cuando exista.', 'Haz clic en Productos y busca la tarjeta del producto.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('CATALOGO', 'CU-GO-022', 'Publicar u ocultar producto de la vitrina', 'Administrador', 'Controlar qué productos aparecen en el catálogo público sin borrar información interna.', 'Haz clic en Productos y edita el producto.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('COTIZACIONES', 'CU-GO-030', 'Crear cotización para torta o mesa dulce', 'Atención al cliente', 'Preparar una propuesta antes de confirmar un encargo especial.', 'Haz clic en Cotizaciones desde el menú lateral.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('COTIZACIONES', 'CU-GO-031', 'Convertir cotización aprobada en pedido', 'Atención al cliente', 'Pasar una propuesta aceptada a compromiso real de entrega.', 'Haz clic en Cotizaciones y ubica la propuesta aprobada.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('COTIZACIONES', 'CU-GO-032', 'Dar seguimiento a cotizaciones pendientes', 'Administrador o atención', 'Evitar que propuestas comerciales queden olvidadas.', 'Haz clic en Cotizaciones y filtra pendientes.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('PEDIDOS', 'CU-GO-040', 'Registrar pedido confirmado', 'Atención al cliente', 'Crear el pedido real cuando ya existe acuerdo de compra o entrega.', 'Haz clic en Pedidos desde el menú lateral.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('PEDIDOS', 'CU-GO-041', 'Actualizar estado de pedido', 'Atención o producción', 'Mantener visible si el pedido está registrado, en preparación, listo o entregado.', 'Haz clic en Pedidos y ubica el pedido.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('PEDIDOS', 'CU-GO-042', 'Cerrar pedido entregado', 'Atención al cliente', 'Cerrar correctamente la venta cuando el cliente retira o recibe el producto.', 'Haz clic en Pedidos y revisa pedidos listos.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('PRODUCCION', 'CU-GO-050', 'Organizar cola de producción', 'Producción', 'Priorizar horneo, relleno, decoración y empaque según fechas de entrega.', 'Haz clic en Producción desde el menú lateral.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('PRODUCCION', 'CU-GO-051', 'Registrar avance de cocina', 'Producción', 'Dejar constancia del avance real para que atención no dependa de preguntar en cocina.', 'Haz clic en Producción y abre el pedido correspondiente.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('PRODUCCION', 'CU-GO-052', 'Consultar receta antes de preparar', 'Producción', 'Usar la receta técnica del producto para mantener consistencia.', 'Puedes iniciar desde Producción o Productos.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('DECORACION_EMPAQUE', 'CU-GO-060', 'Verificar decoración final', 'Producción o decoración', 'Comparar el producto terminado contra las notas del pedido antes de empacar.', 'Haz clic en Producción o Pedidos y abre el encargo.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('DECORACION_EMPAQUE', 'CU-GO-061', 'Confirmar empaque y salida', 'Producción o atención', 'Evitar entregar productos sin protección o con datos de cliente equivocados.', 'Haz clic en Pedidos y revisa pedidos listos.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('DECORACION_EMPAQUE', 'CU-GO-062', 'Registrar incidencia de entrega', 'Atención al cliente', 'Dejar anotado cualquier cambio, daño, retraso o ajuste antes de cerrar el pedido.', 'Haz clic en Pedidos y abre el pedido afectado.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('ABASTECIMIENTO', 'CU-GO-070', 'Revisar insumos críticos', 'Administrador o compras', 'Detectar mínimos de ingredientes, empaques o insumos antes de afectar producción.', 'Haz clic en Abastecimiento desde el menú lateral.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('ABASTECIMIENTO', 'CU-GO-071', 'Registrar movimiento de inventario', 'Administrador o compras', 'Mantener entradas, salidas, mermas y ajustes visibles para el negocio.', 'Haz clic en Abastecimiento y luego Inventario.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('ABASTECIMIENTO', 'CU-GO-072', 'Crear orden de compra', 'Administrador o compras', 'Preparar una compra con proveedor antes de recibir mercadería.', 'Haz clic en Abastecimiento y entra a Compras.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('RECETAS', 'CU-GO-080', 'Consultar receta técnica desde Productos', 'Producción', 'Descargar una ficha clara con logo, imagen del postre, ingredientes y preparación.', 'Haz clic en Productos desde el menú lateral.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('RECETAS', 'CU-GO-081', 'Editar receta de producto', 'Administrador o producción autorizada', 'Actualizar ingredientes, pasos y observaciones cuando cambie la preparación.', 'Haz clic en Productos y edita el producto.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('RECETAS', 'CU-GO-082', 'Usar receta para calcular producción', 'Producción', 'Leer cantidades y pasos antes de preparar varios productos similares.', 'Haz clic en Productos o Producción según el punto de partida.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('PROVEEDORES', 'CU-GO-090', 'Registrar proveedor nuevo', 'Administrador o compras', 'Guardar contacto y datos básicos de quien abastece insumos o empaques.', 'Haz clic en Abastecimiento y luego Proveedores.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('PROVEEDORES', 'CU-GO-091', 'Asociar insumo con proveedor', 'Administrador o compras', 'Saber quién vende cada insumo y con qué precio o presentación.', 'Haz clic en Abastecimiento y revisa proveedor o insumo.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('PROVEEDORES', 'CU-GO-092', 'Desactivar proveedor problemático', 'Administrador', 'Evitar usar proveedores que ya no trabajan con el local o entregan mal.', 'Haz clic en Abastecimiento y luego Proveedores.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('REPORTES', 'CU-GO-100', 'Generar reporte de negocio', 'Administrador', 'Crear un archivo PDF o reporte interno para revisar ventas, pedidos y producción.', 'Haz clic en Reportes desde el menú lateral.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('REPORTES', 'CU-GO-101', 'Revisar reportes generados', 'Administrador', 'Consultar archivos anteriores sin volver a calcular todo innecesariamente.', 'Haz clic en Reportes y revisa la lista.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('REPORTES', 'CU-GO-102', 'Usar reportes para decidir compras', 'Administrador', 'Relacionar ventas y producción con necesidades de abastecimiento.', 'Empieza desde Reportes y luego Abastecimiento.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('NOTIFICACIONES', 'CU-GO-110', 'Leer notificaciones pendientes', 'Usuario del sistema', 'Enterarse de avisos internos sin revisar todos los módulos.', 'Haz clic en Notificaciones desde el resumen o menú superior.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('NOTIFICACIONES', 'CU-GO-111', 'Archivar notificaciones atendidas', 'Usuario del sistema', 'Mantener la bandeja limpia sin perder señales importantes.', 'Haz clic en Notificaciones y revisa las atendidas.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('NOTIFICACIONES', 'CU-GO-112', 'Usar avisos para cambiar de módulo', 'Usuario del sistema', 'Saltar desde un aviso hacia el área que necesita atención.', 'Haz clic en Notificaciones.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('USUARIOS', 'CU-GO-120', 'Crear usuario interno', 'Administrador', 'Dar acceso individual a una persona del equipo sin compartir credenciales.', 'Haz clic en Usuarios si el módulo está habilitado para administración.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('USUARIOS', 'CU-GO-121', 'Cambiar rol o permiso', 'Administrador', 'Ajustar accesos cuando una persona cambia de responsabilidad.', 'Haz clic en Usuarios y busca la cuenta.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('USUARIOS', 'CU-GO-122', 'Desactivar usuario', 'Administrador', 'Bloquear acceso cuando una persona ya no debe entrar al sistema.', 'Haz clic en Usuarios y localiza la cuenta.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('GUIA_OPERATIVA', 'CU-GO-130', 'Consultar la guía operativa', 'Cualquier usuario interno', 'Recordar el flujo correcto de cada área sin depender de memoria ni instrucciones sueltas.', 'Haz clic en Guía operativa desde el menú lateral.', 1, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('GUIA_OPERATIVA', 'CU-GO-131', 'Capacitar a alguien con la guía', 'Administrador o responsable de turno', 'Usar la guía como apoyo de entrenamiento para personal nuevo.', 'Haz clic en Guía operativa durante la capacitación.', 2, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0),
  ('GUIA_OPERATIVA', 'CU-GO-132', 'Detectar procedimiento desactualizado', 'Usuario interno', 'Reportar cuando la operación real ya no coincide con la guía escrita.', 'Haz clic en Guía operativa y abre el caso dudoso.', 3, 'LISTO', 2, NOW(), TRUE, NOW(), NOW(), 0)
ON CONFLICT (codigo) DO UPDATE SET
  modulo = EXCLUDED.modulo,
  titulo = EXCLUDED.titulo,
  actor_principal = EXCLUDED.actor_principal,
  objetivo = EXCLUDED.objetivo,
  punto_inicio = EXCLUDED.punto_inicio,
  orden_visual = EXCLUDED.orden_visual,
  estado = EXCLUDED.estado,
  version_flujo = EXCLUDED.version_flujo,
  actualizado_en = NOW(),
  activo = EXCLUDED.activo,
  updated_at = NOW();

WITH step_seed(codigo, numero, descripcion) AS (
  VALUES
  ('CU-GO-001', 1, 'Haz clic en Resumen en el menú lateral izquierdo.'),
  ('CU-GO-001', 2, 'Revisa la tarjeta Caja del día para confirmar el dinero cerrado en pedidos entregados.'),
  ('CU-GO-001', 3, 'Revisa Clientes activos, Cotizaciones pendientes, Pedidos listos y Producción activa.'),
  ('CU-GO-001', 4, 'Haz clic en Actualizar datos si necesitas refrescar el pulso del negocio.'),
  ('CU-GO-001', 5, 'Usa las alertas superiores para decidir si debes entrar a Pedidos, Producción, Abastecimiento o Reportes.'),
  ('CU-GO-002', 1, 'Haz clic en Notificaciones, arriba a la derecha del resumen.'),
  ('CU-GO-002', 2, 'Lee primero los avisos marcados como pendientes o de prioridad alta.'),
  ('CU-GO-002', 3, 'Haz clic en el módulo relacionado si el aviso menciona pedidos, producción, reportes o abastecimiento.'),
  ('CU-GO-002', 4, 'Cuando el aviso ya esté resuelto, márcalo como leído o archívalo desde Notificaciones.'),
  ('CU-GO-002', 5, 'No cierres avisos críticos si todavía falta una acción humana.'),
  ('CU-GO-003', 1, 'Haz clic en Resumen en el menú lateral.'),
  ('CU-GO-003', 2, 'Mira la tarjeta Meta mínima semanal y compara el porcentaje con el valor esperado.'),
  ('CU-GO-003', 3, 'Si el porcentaje está bajo, haz clic en Cotizaciones para revisar propuestas pendientes.'),
  ('CU-GO-003', 4, 'Si hay pedidos listos, haz clic en Pedidos para confirmar entrega o cierre.'),
  ('CU-GO-003', 5, 'Usa esta lectura como señal; no reemplaza revisar el detalle comercial.'),
  ('CU-GO-010', 1, 'Haz clic en Clientes en el menú lateral izquierdo.'),
  ('CU-GO-010', 2, 'Haz clic en el formulario Nuevo cliente o en el área de registro disponible.'),
  ('CU-GO-010', 3, 'Escribe nombre completo, teléfono y correo si el cliente lo proporciona.'),
  ('CU-GO-010', 4, 'Agrega observaciones útiles: alergias informadas, retiro en local, entrega o preferencia recurrente.'),
  ('CU-GO-010', 5, 'Haz clic en Registrar cliente y verifica que aparezca en la lista.'),
  ('CU-GO-011', 1, 'Haz clic en Clientes en el menú lateral.'),
  ('CU-GO-011', 2, 'Usa la lista o búsqueda para ubicar al cliente antes de crear otro registro.'),
  ('CU-GO-011', 3, 'Haz clic en Editar en la tarjeta o fila del cliente.'),
  ('CU-GO-011', 4, 'Corrige teléfono, correo u observaciones necesarias.'),
  ('CU-GO-011', 5, 'Haz clic en Guardar cambios y confirma que el dato actualizado se mantenga.'),
  ('CU-GO-012', 1, 'Haz clic en Clientes y confirma que la persona existe.'),
  ('CU-GO-012', 2, 'Si no existe, registra primero al cliente.'),
  ('CU-GO-012', 3, 'Haz clic en Cotizaciones o Pedidos según el caso.'),
  ('CU-GO-012', 4, 'Selecciona el cliente en el formulario correspondiente.'),
  ('CU-GO-012', 5, 'Guarda la operación para que el historial comercial quede asociado.'),
  ('CU-GO-020', 1, 'Haz clic en Productos en el menú lateral.'),
  ('CU-GO-020', 2, 'En el formulario Nuevo producto, elige la categoría y escribe código, nombre y descripción.'),
  ('CU-GO-020', 3, 'Completa precio base y marca si requiere cotización previa.'),
  ('CU-GO-020', 4, 'Haz clic en Foto del producto para subir una imagen cuadrada sobre fondo limpio.'),
  ('CU-GO-020', 5, 'Haz clic en Registrar producto y revisa que aparezca en el catálogo administrativo.'),
  ('CU-GO-021', 1, 'Haz clic en Productos en el menú lateral.'),
  ('CU-GO-021', 2, 'Busca la tarjeta del producto que necesitas revisar.'),
  ('CU-GO-021', 3, 'Haz clic en Editar para cargar sus datos en el formulario.'),
  ('CU-GO-021', 4, 'Si solo necesitas la ficha técnica, haz clic en Descargar receta PDF en la tarjeta del producto.'),
  ('CU-GO-021', 5, 'Abre el PDF descargado y verifica logo, imagen del postre, ingredientes y preparación.'),
  ('CU-GO-022', 1, 'Haz clic en Productos en el menú lateral.'),
  ('CU-GO-022', 2, 'Haz clic en Editar sobre el producto correspondiente.'),
  ('CU-GO-022', 3, 'Marca Producto activo si se puede vender internamente.'),
  ('CU-GO-022', 4, 'Marca Visible en catálogo público si debe mostrarse en la landing.'),
  ('CU-GO-022', 5, 'Haz clic en Guardar cambios y revisa la vitrina pública si corresponde.'),
  ('CU-GO-030', 1, 'Haz clic en Cotizaciones en el menú lateral.'),
  ('CU-GO-030', 2, 'Haz clic en Nueva cotización o usa el formulario visible.'),
  ('CU-GO-030', 3, 'Selecciona el cliente; si no existe, ve primero a Clientes y regístralo.'),
  ('CU-GO-030', 4, 'Agrega productos, cantidades, notas de decoración, fecha tentativa y precio estimado.'),
  ('CU-GO-030', 5, 'Haz clic en Guardar cotización y revisa que quede pendiente o aprobada según el caso.'),
  ('CU-GO-031', 1, 'Haz clic en Cotizaciones en el menú lateral.'),
  ('CU-GO-031', 2, 'Busca la cotización aprobada por el cliente.'),
  ('CU-GO-031', 3, 'Revisa productos, cantidades, total y observaciones antes de convertir.'),
  ('CU-GO-031', 4, 'Haz clic en Convertir a pedido si la opción está disponible, o registra el pedido manualmente con los mismos datos.'),
  ('CU-GO-031', 5, 'Confirma fecha de entrega y prioridad en el módulo Pedidos.'),
  ('CU-GO-032', 1, 'Haz clic en Cotizaciones en el menú lateral.'),
  ('CU-GO-032', 2, 'Revisa las cotizaciones con estado Pendiente.'),
  ('CU-GO-032', 3, 'Haz clic en la cotización para leer notas, productos y fecha probable.'),
  ('CU-GO-032', 4, 'Contacta al cliente por el canal registrado y actualiza observaciones si aplica.'),
  ('CU-GO-032', 5, 'Cambia el estado cuando el cliente apruebe, rechace o pida ajuste.'),
  ('CU-GO-040', 1, 'Haz clic en Pedidos en el menú lateral.'),
  ('CU-GO-040', 2, 'Haz clic en Nuevo pedido o usa el formulario de registro.'),
  ('CU-GO-040', 3, 'Selecciona cliente, fecha estimada, prioridad y origen del pedido.'),
  ('CU-GO-040', 4, 'Agrega productos, cantidades, precio y notas de preparación o decoración.'),
  ('CU-GO-040', 5, 'Haz clic en Registrar pedido y confirma que aparezca en la lista.'),
  ('CU-GO-041', 1, 'Haz clic en Pedidos en el menú lateral.'),
  ('CU-GO-041', 2, 'Busca el pedido por código, cliente o fecha cercana.'),
  ('CU-GO-041', 3, 'Haz clic en el control de estado del pedido.'),
  ('CU-GO-041', 4, 'Cambia el estado solo cuando la acción real ya ocurrió.'),
  ('CU-GO-041', 5, 'Verifica que el cambio se refleje también en Resumen y Producción si corresponde.'),
  ('CU-GO-042', 1, 'Haz clic en Pedidos en el menú lateral.'),
  ('CU-GO-042', 2, 'Filtra o localiza los pedidos listos para salida.'),
  ('CU-GO-042', 3, 'Confirma físicamente el producto, empaque, nombre del cliente y observaciones.'),
  ('CU-GO-042', 4, 'Haz clic en el estado Entregado solo cuando la entrega o retiro ya fue confirmado.'),
  ('CU-GO-042', 5, 'Revisa que el cierre alimente la caja del día y el resumen semanal.'),
  ('CU-GO-050', 1, 'Haz clic en Producción en el menú lateral.'),
  ('CU-GO-050', 2, 'Revisa los pedidos ordenados por fecha de entrega y prioridad.'),
  ('CU-GO-050', 3, 'Haz clic en el pedido o tarjeta de producción que vas a trabajar.'),
  ('CU-GO-050', 4, 'Lee notas de relleno, decoración, empaque y horario.'),
  ('CU-GO-050', 5, 'Actualiza el estado cuando avances de etapa.'),
  ('CU-GO-051', 1, 'Haz clic en Producción en el menú lateral.'),
  ('CU-GO-051', 2, 'Ubica el pedido en preparación.'),
  ('CU-GO-051', 3, 'Haz clic en el control de estado o acción disponible.'),
  ('CU-GO-051', 4, 'Cambia a horneo, decoración, listo o el estado equivalente según el flujo visible.'),
  ('CU-GO-051', 5, 'Agrega observaciones si falta insumo, hubo retraso o se cambió la decoración.'),
  ('CU-GO-052', 1, 'Haz clic en Productos si necesitas la receta técnica del producto.'),
  ('CU-GO-052', 2, 'Busca la tarjeta del producto que vas a preparar.'),
  ('CU-GO-052', 3, 'Haz clic en Descargar receta PDF.'),
  ('CU-GO-052', 4, 'Revisa ingredientes, pasos y observaciones antes de iniciar el lote.'),
  ('CU-GO-052', 5, 'Vuelve a Producción y actualiza el avance del pedido.'),
  ('CU-GO-060', 1, 'Haz clic en Producción o Pedidos según dónde estés trabajando.'),
  ('CU-GO-060', 2, 'Abre el pedido que está en etapa de decoración.'),
  ('CU-GO-060', 3, 'Lee notas de color, dedicatoria, relleno, tamaño y empaque.'),
  ('CU-GO-060', 4, 'Compara la decoración física con lo solicitado por el cliente.'),
  ('CU-GO-060', 5, 'Si está correcto, avanza el estado a listo para empaque o salida.'),
  ('CU-GO-061', 1, 'Haz clic en Pedidos en el menú lateral.'),
  ('CU-GO-061', 2, 'Busca los pedidos en estado Listo o Listo para salida.'),
  ('CU-GO-061', 3, 'Confirma nombre del cliente, producto, cantidad y hora de entrega.'),
  ('CU-GO-061', 4, 'Verifica que el empaque sea adecuado para retiro o entrega.'),
  ('CU-GO-061', 5, 'Cambia el estado cuando el producto realmente sale del local.'),
  ('CU-GO-062', 1, 'Haz clic en Pedidos en el menú lateral.'),
  ('CU-GO-062', 2, 'Abre o edita el pedido afectado.'),
  ('CU-GO-062', 3, 'Escribe una observación clara: qué pasó, quién avisó y qué solución se dio.'),
  ('CU-GO-062', 4, 'Si hace falta, mantén el pedido sin cerrar hasta resolverlo.'),
  ('CU-GO-062', 5, 'Cuando se solucione, actualiza el estado y deja la trazabilidad mínima.'),
  ('CU-GO-070', 1, 'Haz clic en Abastecimiento en el menú lateral.'),
  ('CU-GO-070', 2, 'Entra al Dashboard de abastecimiento.'),
  ('CU-GO-070', 3, 'Revisa alertas de stock mínimo e insumos críticos.'),
  ('CU-GO-070', 4, 'Haz clic en Inventario para revisar existencias y movimientos.'),
  ('CU-GO-070', 5, 'Prioriza la reposición de lo que afecte pedidos cercanos.'),
  ('CU-GO-071', 1, 'Haz clic en Abastecimiento en el menú lateral.'),
  ('CU-GO-071', 2, 'Haz clic en Inventario o Movimientos.'),
  ('CU-GO-071', 3, 'Elige el insumo o ingrediente afectado.'),
  ('CU-GO-071', 4, 'Registra entrada, salida, merma o ajuste con cantidad y motivo.'),
  ('CU-GO-071', 5, 'Guarda el movimiento y revisa que el stock haya cambiado correctamente.'),
  ('CU-GO-072', 1, 'Haz clic en Abastecimiento en el menú lateral.'),
  ('CU-GO-072', 2, 'Haz clic en Compras.'),
  ('CU-GO-072', 3, 'Selecciona proveedor y agrega los insumos o productos necesarios.'),
  ('CU-GO-072', 4, 'Revisa cantidades, costo estimado y observaciones.'),
  ('CU-GO-072', 5, 'Haz clic en Guardar orden de compra y cambia el estado cuando sea recibida.'),
  ('CU-GO-080', 1, 'Haz clic en Productos en el menú lateral.'),
  ('CU-GO-080', 2, 'Busca la tarjeta del producto que vas a preparar.'),
  ('CU-GO-080', 3, 'Haz clic en Descargar receta PDF o en el botón Receta PDF.'),
  ('CU-GO-080', 4, 'Abre el archivo descargado y revisa ingredientes, pasos y observaciones.'),
  ('CU-GO-080', 5, 'Usa la receta como guía técnica antes de producir.'),
  ('CU-GO-081', 1, 'Haz clic en Productos en el menú lateral.'),
  ('CU-GO-081', 2, 'Haz clic en Editar sobre el producto correspondiente.'),
  ('CU-GO-081', 3, 'Baja hasta la sección Receta del producto.'),
  ('CU-GO-081', 4, 'Edita título, ingredientes, preparación y notas.'),
  ('CU-GO-081', 5, 'Haz clic en Guardar cambios y descarga el PDF para verificar el resultado.'),
  ('CU-GO-082', 1, 'Haz clic en Productos para abrir la ficha técnica del producto.'),
  ('CU-GO-082', 2, 'Descarga la receta PDF si necesitas imprimirla o compartirla en cocina.'),
  ('CU-GO-082', 3, 'Revisa rendimiento, cantidades y pasos antes de preparar el lote.'),
  ('CU-GO-082', 4, 'Ve a Producción para ubicar pedidos relacionados.'),
  ('CU-GO-082', 5, 'Actualiza estados cuando el lote avance de etapa.'),
  ('CU-GO-090', 1, 'Haz clic en Abastecimiento en el menú lateral.'),
  ('CU-GO-090', 2, 'Haz clic en Proveedores.'),
  ('CU-GO-090', 3, 'Haz clic en Nuevo proveedor o usa el formulario visible.'),
  ('CU-GO-090', 4, 'Escribe nombre, teléfono, correo y observaciones útiles.'),
  ('CU-GO-090', 5, 'Haz clic en Guardar proveedor y verifica que aparezca activo.'),
  ('CU-GO-091', 1, 'Haz clic en Abastecimiento en el menú lateral.'),
  ('CU-GO-091', 2, 'Entra a Proveedores o Items proveedor.'),
  ('CU-GO-091', 3, 'Selecciona el proveedor correspondiente.'),
  ('CU-GO-091', 4, 'Asocia el insumo, presentación, costo o referencia comercial.'),
  ('CU-GO-091', 5, 'Guarda la relación para que las compras futuras sean más rápidas.'),
  ('CU-GO-092', 1, 'Haz clic en Abastecimiento en el menú lateral.'),
  ('CU-GO-092', 2, 'Haz clic en Proveedores.'),
  ('CU-GO-092', 3, 'Busca el proveedor que ya no debe usarse.'),
  ('CU-GO-092', 4, 'Haz clic en Desactivar o cambia su estado a inactivo.'),
  ('CU-GO-092', 5, 'Escribe una observación si hubo incumplimiento, cambio de precio o entrega incompleta.'),
  ('CU-GO-100', 1, 'Haz clic en Reportes en el menú lateral.'),
  ('CU-GO-100', 2, 'Elige el tipo de reporte que necesitas generar.'),
  ('CU-GO-100', 3, 'Haz clic en Generar reporte.'),
  ('CU-GO-100', 4, 'Espera a que el estado cambie a Completado.'),
  ('CU-GO-100', 5, 'Haz clic en Descargar cuando el archivo esté listo.'),
  ('CU-GO-101', 1, 'Haz clic en Reportes en el menú lateral.'),
  ('CU-GO-101', 2, 'Revisa la tabla o tarjetas de reportes recientes.'),
  ('CU-GO-101', 3, 'Mira estado, fecha y tipo de reporte.'),
  ('CU-GO-101', 4, 'Haz clic en Descargar si el archivo todavía está disponible.'),
  ('CU-GO-101', 5, 'Limpia o archiva reportes antiguos si ya no aportan valor.'),
  ('CU-GO-102', 1, 'Haz clic en Reportes y genera un resumen de negocio o producción.'),
  ('CU-GO-102', 2, 'Revisa productos más pedidos, carga de producción y pedidos cercanos.'),
  ('CU-GO-102', 3, 'Haz clic en Abastecimiento para revisar mínimos de insumos.'),
  ('CU-GO-102', 4, 'Crea una orden de compra si el reporte muestra riesgo de faltante.'),
  ('CU-GO-102', 5, 'Usa el reporte como apoyo, no como reemplazo del criterio humano.'),
  ('CU-GO-110', 1, 'Haz clic en Notificaciones en la parte superior del panel.'),
  ('CU-GO-110', 2, 'Lee primero las notificaciones nuevas o críticas.'),
  ('CU-GO-110', 3, 'Identifica si pertenecen a pedidos, producción, abastecimiento o reportes.'),
  ('CU-GO-110', 4, 'Haz clic en el módulo relacionado para resolver la causa.'),
  ('CU-GO-110', 5, 'Marca la notificación como leída cuando la acción esté atendida.'),
  ('CU-GO-111', 1, 'Haz clic en Notificaciones.'),
  ('CU-GO-111', 2, 'Revisa qué avisos ya fueron resueltos.'),
  ('CU-GO-111', 3, 'Selecciona los avisos atendidos o usa la acción de archivar leídas.'),
  ('CU-GO-111', 4, 'Haz clic en Archivar.'),
  ('CU-GO-111', 5, 'No archives avisos críticos si todavía falta una acción real.'),
  ('CU-GO-112', 1, 'Haz clic en Notificaciones.'),
  ('CU-GO-112', 2, 'Lee el texto del aviso y detecta qué módulo menciona.'),
  ('CU-GO-112', 3, 'Haz clic en Pedidos, Producción, Abastecimiento o Reportes según corresponda.'),
  ('CU-GO-112', 4, 'Resuelve la acción pendiente en ese módulo.'),
  ('CU-GO-112', 5, 'Vuelve a Notificaciones y marca el aviso como atendido.'),
  ('CU-GO-120', 1, 'Haz clic en Usuarios o en la sección de administración de accesos.'),
  ('CU-GO-120', 2, 'Haz clic en Nuevo usuario.'),
  ('CU-GO-120', 3, 'Escribe usuario, nombre visible y contraseña inicial segura.'),
  ('CU-GO-120', 4, 'Asigna el rol correcto: administración, atención o producción.'),
  ('CU-GO-120', 5, 'Haz clic en Guardar y comunica la cuenta solo a la persona correspondiente.'),
  ('CU-GO-121', 1, 'Haz clic en Usuarios.'),
  ('CU-GO-121', 2, 'Busca la cuenta de la persona.'),
  ('CU-GO-121', 3, 'Haz clic en Editar.'),
  ('CU-GO-121', 4, 'Cambia el rol solo si la responsabilidad real cambió.'),
  ('CU-GO-121', 5, 'Guarda y pide al usuario cerrar sesión e ingresar nuevamente.'),
  ('CU-GO-122', 1, 'Haz clic en Usuarios.'),
  ('CU-GO-122', 2, 'Busca la cuenta que debe quedar sin acceso.'),
  ('CU-GO-122', 3, 'Haz clic en Desactivar o cambia el estado a inactivo.'),
  ('CU-GO-122', 4, 'Confirma la acción y registra una observación interna si aplica.'),
  ('CU-GO-122', 5, 'No borres cuentas si sirven para trazabilidad histórica.'),
  ('CU-GO-130', 1, 'Haz clic en Guía operativa en el menú lateral izquierdo.'),
  ('CU-GO-130', 2, 'Haz clic en el área de trabajo que corresponde a tu duda.'),
  ('CU-GO-130', 3, 'Haz clic en el procedimiento específico dentro de esa área.'),
  ('CU-GO-130', 4, 'Lee objetivo, responsable, punto de inicio y pasos.'),
  ('CU-GO-130', 5, 'Vuelve al módulo real y ejecuta la acción siguiendo el criterio del negocio.'),
  ('CU-GO-131', 1, 'Haz clic en Guía operativa.'),
  ('CU-GO-131', 2, 'Selecciona el área que la persona va a usar primero.'),
  ('CU-GO-131', 3, 'Lee en voz alta el procedimiento y muestra dónde se hace clic en el sistema.'),
  ('CU-GO-131', 4, 'Pide a la persona repetir el flujo en el módulo real.'),
  ('CU-GO-131', 5, 'Anota qué pasos causaron duda para mejorar la guía después.'),
  ('CU-GO-132', 1, 'Haz clic en Guía operativa.'),
  ('CU-GO-132', 2, 'Abre el procedimiento que parece desactualizado.'),
  ('CU-GO-132', 3, 'Compara los pasos con lo que realmente se hace en el local.'),
  ('CU-GO-132', 4, 'Anota qué botón, módulo o decisión ya cambió.'),
  ('CU-GO-132', 5, 'Avisa a administración o soporte para actualizar la documentación.')
)
INSERT INTO paso_caso_uso (caso_uso_id, numero, descripcion, created_at, updated_at, version)
SELECT cu.caso_uso_id, step_seed.numero, step_seed.descripcion, NOW(), NOW(), 0
FROM step_seed
JOIN caso_uso_operativo cu ON cu.codigo = step_seed.codigo
ON CONFLICT (caso_uso_id, numero) DO UPDATE SET
  descripcion = EXCLUDED.descripcion,
  updated_at = NOW();
